### ISSUE TITLE
Add support for Grml Live Linux.

### ISSUE THREAD

**Issue by RemoteDataServicesDotNet** [PJ-Singh-001/Cubic#93] opened 2022-08-17 00:36 UTC
Perhaps not a bug but the .iso for grml.org places it's squashfs extension two levels under source-disk like so...
 
source-disk/live/grml64-full/grml64-full.squashfs

....which I expect is the reason Cubic could not find grml's squashfs. Can Cubic be modified to allow for this?

And thanks for making Cubic. It's most useful!

**Comment by PJ-Singh-001** [comment] 2022-08-17 23:15
You are correct this is not a bug.
Cubic only works with distributions based on Ubuntu.
Even though Ubuntu is based on Debian, we still require the "base" Ubuntu ISO structure.

**Comment by PJ-Singh-001** [comment] 2022-08-18 03:25
To answer your second question, I have looked into modifying Cubic to use a Debian-based ISO, but the structure is significantly different from what Canonical did with Ubuntu, so this is not feasible. I may revisit this in the future, but there are no immediate plans to do this.

**Comment by RemoteDataServicesDotNet** [comment] 2022-08-18 12:48
Well I tried to Cubicize Debian Standard version and it seems to have worked...  https://i.imgur.com/oX1aFGd.png

**Comment by RemoteDataServicesDotNet** [comment] 2022-08-18 20:13
But it is broken. The Cubic Debian iso gets to the boot screen but it will not go beyond that. Oh well.

**Comment by PJ-Singh-001** [comment] 2022-08-18 21:00
It sounds like you are able to get to the [Terminal page](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page) in Cubic while customizing the Debian ISO.
This is good news.

Here is a "trick" you may try...

1. Download an official Ubuntu ISO, like `ubuntu-20.04.3-desktop-amd64.iso`.
2. Also, make sure you still have the Debian ISO that you used in your [experiment above](https://github.com/PJ-Singh-001/Cubic/issues/93#issuecomment-1219452169).
3. Start a new Cubic project.
4. Choose to customize your Debian ISO ([as you did before](https://github.com/PJ-Singh-001/Cubic/issues/93#issuecomment-1219452169)).
5. After you (successfully) arrive at the [Terminal page](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page), click the <kbd>Back</kbd> button to return to the [Project page](https://github.com/PJ-Singh-001/Cubic/wiki/Project-Page).
6. In the "Original Disk" section on the left side of the page, click on the Folder button <kbd>![image](https://user-images.githubusercontent.com/19394936/185492617-f67b2e3c-4bc7-42ad-a97e-32aac12f6402.png)</kbd> next to "Filename".
7. At this point, select an official "Ubuntu" ISO, like `ubuntu-20.04.3-desktop-amd64.iso`.
    Cubic will attempt to use the Ubuntu ISO file structure, from the ISO you choose, while still allowing you to customize Debian Linux on Cubic's [Terminal page](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page).
8. Click the <kbd>Customize</kbd> button to continue customizing Debian.

I can't guarantee this will work, but please let me know the results if you try it.

**Comment by PJ-Singh-001** [comment] 2022-10-13 00:59
@RemoteDataServicesDotNet,

Did the above "trick" work for you?

**Comment by RemoteDataServicesDotNet** [comment] 2022-10-13 01:50
Sorry it was a while ago. So my memory is a bit cloudy. But as I recall the
trick allowed me to generate a customized iso but the iso would not boot.

So I switched to another grml friendly solution. Not as nice as Cubic
though.

**Comment by PJ-Singh-001** [comment] 2022-10-19 00:25
I've figured out a way to make Cubic work with grml.org.
It will require a code change, and I will include it in the next release.

**Comment by RemoteDataServicesDotNet** [comment] 2022-10-19 03:21
This is great news. Thank you!  If you should ever need help with data
recovery. I'll take care of you.

**Comment by PJ-Singh-001** [comment] 2022-10-20 19:34
Lol! I do appreciate it.
I'll let you know when the next release is out. It may be a few weeks.

**Comment by PJ-Singh-001** [comment] 2022-11-10 02:06
Grml Live Linux uses the following squashfs file:
- `grml64-full.squashfs`

Grml Live Linux uses the following boot configuration files:
- `boot/grub/grml64full_default.cfg`
- `boot/grub/grml64full_options.cfg`
- `boot/isolinux/grml.cfg`
- `boot/isolinux/hidden.cfg`

**Comment by PJ-Singh-001** [comment] 2022-11-12 16:25
Adding simultaneous support for multiple Distros generically is complex due to different combinations of directories for the kernel files, multiple sets of kernel files, and different directories for `squashfs`.

In Ubuntu, the kernel files (`vmlinuz` and `initrd`) are located in the `casper` directory, along with the `squashfs` file system. This is the simplest situation, which Cubic already handles (even if the `casper` directory has a different name).

In Debian, there are two sets of kernel files (`vmlinuz` and `initrd`). One set is located in the `d-i` directory, and the other set is located in the `live` directory. _Which of these sets should Cubic update/overwrite? Is one set used for the live environment, whereas another set is used to install the OS?_ There is only one `squashfs` file system; however, it is located in a different directory, `live`.

In Grml Live Linux, the kernel files (`vmlinuz` and `initrd`) are located in the `boot/grml64full` directory. There is only one `squashfs` file system; however, it is located in a different directory, `/live/grml64-full`.

For Pop_OS!, there is also a symlink `casper -> casper_pop-os_21.10_amd64_intel_debug_59` that results in the following paths. The above paths work for `vmlinuz` and `initrd`, but the `boot=` path requires `casper` because an `init` requires it during boot.

The combinations of different directories for the kernel files, multiple sets of kernel files, and different directories for `squashfs` are complex. Furthermore, there are numerous and varying boot configuration files that must be automatically and consistently updated to reference these files correctly.

**Ubuntu ISO**

    /casper/vmlinuz

    /casper/initrd

    /casper/filesystem.squashfs

**Ubuntu Live Server (22.04)**

    /casper/vmlinuz

    /casper/initrd

    /casper/ubuntu-server-minimal.squashfs
    /casper/ubuntu-server-minimal.ubuntu-server.installer.generic.squashfs
    /casper/ubuntu-server-minimal.ubuntu-server.installer.squashfs
    /casper/ubuntu-server-minimal.ubuntu-server.squashfs


**Debian ISO**

    /d-i/gtk/vmlinuz
    /d-i/vmlinuz
    /live/vmlinuz-5.10.0-18-amd64

    /d-i/gtk/initrd.gz
    /d-i/initrd.gz
    /live/initrd.img-5.10.0-18-amd64

    /live/filesystem.squashfs


**Grml Live Linux ISO**

    /boot/grml64full/vmlinuz

    /boot/grml64full/initrd.img

    /live/grml64-full/grml64-full.squashfs

**Pop_OS! 21.10**

    /casper_pop-os_21.10_amd64_intel_debug_59/vmlinuz.efi

    /casper_pop-os_21.10_amd64_intel_debug_59/initrd.gz

    /casper_pop-os_21.10_amd64_intel_debug_59/filesystem.squashfs

    /casper -> casper_pop-os_21.10_amd64_intel_debug_59

    /casper/vmlinuz.efi

    /casper/initrd.gz

    /casper/filesystem.squashfs

**Comment by PJ-Singh-001** [comment] 2022-11-20 00:57
**Linux File System (`*.squashfs`)**

 1. If multiple `squashfs` files are identified, such as with Ubuntu Live Server 22.04+, then chose to use the file matching `filesystem.squashfs`, `ubuntu-server-minimal.squashfs`, or `grml64-full.squashfs` (in that order). (This predefined list of `squashfs` files in the `constants` module may be updated as necessary in future releases to accommodate other distributions. Note: `filesystem.squashfs` and `grml64-full.squashfs` are unnecessary and should be removed from this list in the next release.)
 2. The list of predefined `squashfs` file names will _only_ be used if there are more than one `squashfs` files identified, so distributions that use other `squashfs` file names will still work, as long as there is only one `squashfs` file. (Previously, selected `squashfs` files were required to be in the list: `filesystem.squashfs`, `ubuntu-server-minimal.squashfs`).

**Boot Configuration Files**

 3. Automatically detect boot configuration files, instead of relying on a list of distribution specific boot files in the `constants` module. The detected files will be displayed in the filtered list on the [Boot tab](https://github.com/PJ-Singh-001/Cubic/wiki/Options-Page#boot-tab) of the [Options page](https://github.com/PJ-Singh-001/Cubic/wiki/Options-Page). Per existing functionality, the user can still add other configuration files (that may have been missed) by unfiltering the list and editing the desired file(s), because edited files are automatically included in the list of filtered boot configuration files.
 4. Distinguish between the `casper` directory and `squashfs` directory in the boot configuration files. These directories are the same for Ubuntu based distributions and for Debian, but for other distributions, such as Grml Live Linux ISO, this may not be the case.

**`boot=`**

 5. Improve existing functionality to add the the `boot=` kernel parameter if it is missing. If `boot=` already exists, the configuration line will not be changed.
    1. Add the `boot=` kernel parameter to lines beginning with `append`.
    2. Add the `boot=` kernel parameter to lines beginning with `linux`, only if the next line does not begin with `append`.
 6. The added `boot=` kernel parameter will reference the parent directory for `squashfs`. (Note, although Grml Live Linux ISO uses sub-directories for the `squashfs` file, only the parent directory is listed in the boot configuration files; assume this will also be the case for other Debian based distributions that use sub-directories for the `squashfs` file).

**`vmlinuz` and `initrd`**

 7. Improve existing functionality to update the boot configuration files with the `casper` directory and correct file names for the `vmlinuz` and `initrd` kernel parameters.
 8. If multiple `casper` directories are identified, such as with Debian, then chose to use the directory matching `casper`, `live`, or `boot` (in that order). This predefined list of `casper` directories can be updated as necessary in future releases to accommodate other distributions. This list is _only_ used if there is more than one `casper` directory identified, so distributions that use other `casper` directory names will still work, as long as there is only one `casper` directory.
 9. Update the `vmlinuz` path in lines:
    1. Beginning with `linux`, only if the next line does not begin with `append`
    2. Beginning with `kernel`
10. Update the `initrd` path in lines:
    1. Beginning with `append`
    2. Beginning with `initrd`

**Implementation**

Add an `update_source_view()` function to derived classes of `FilesTab` that need to update files in their files tree and displayable in a `GtkSource.View`. This allows the derived class to provide a specific implementation to modify the file, based on the specific structure of the file. This function is passed to and used by the `FilesTree` class (because the `FilesTree` is responsible for ensuring the file is represented correctly in the tree and that the corresponding `GtkSource.View`. Ultimately, the `FilesTree` class will also save changes to the `GtkSource.View`. The only tab that needs to modify its files is the [Boot tab](https://github.com/PJ-Singh-001/Cubic/wiki/Options-Page#boot-tab), so `BootTab` is the only class that must implement this method (currently).

**Limitations**
 1. If more than one `squashfs` file is detected, and none of the detected files appear in the predefined list of `squashfs` files in the `constants` module, then Cubic will not be able to customize the distribution. The predefined list of `squashfs` files in the `constants` module may be updated as necessary in future releases to accommodate other distributions.
 2. The files `filesystem.squashfs` and `grml64-full.squashfs` included in the predefined list of `squashfs` files in the `constants` module are unnecessary and should be removed from this list in the next release. The inclusion of these files does not negatively impact the behavior of Cubic.
 3. If more than one `casper` directory is detected, and none of the detected directories appear in the predefined list of `casper` directories in the `constants` module, then Cubic will not be able to customize the distribution. The predefined list of `casper` directories in the `constants` module may be updated as necessary in future releases to accommodate other distributions.
 4. The algorithm to add missing `boot=` kernel parameter to lines beginning with `linux` expects the `append` line (if present in the configuration file) to immediately follow the `linux` line. If this is not the case, `boot=` kernel parameter will not be added to the `linux` line, and the user will have to manually add it.
 5. The algorithm updating the `vmlinuz` kernel parameter to lines beginning with `linux` expects the `append` line (if present in the configuration file) to immediately follow the `linux` line. If this is not the case, `vmlinuz` kernel parameter will not be added to the `linux` line, and the user will have to manually add it.
 6. If the `boot=` kernel parameter already exists in the boot configuration file, it is not updated, although it is unlikely that the value of this parameter should need to be updated.
 7. Invoking the `update_source_view()` function in a derived classes of `FilesTab` may impose a performance penalty, and the user may notice this as a slight delay when switching:
    1. from the [Packages page](https://github.com/PJ-Singh-001/Cubic/wiki/Packages-Page) to the [Options page](https://github.com/PJ-Singh-001/Cubic/wiki/Options-Page), or
    2. from the [Kernel tab](https://github.com/PJ-Singh-001/Cubic/wiki/Options-Page#kernel-tab) to the [Boot tab](https://github.com/PJ-Singh-001/Cubic/wiki/Options-Page#boot-tab), if the user changes the selected kernel, or
    3. from the [Options page](https://github.com/PJ-Singh-001/Cubic/wiki/Options-Page) to the [Compression page](https://github.com/PJ-Singh-001/Cubic/wiki/Compression-Page), if the user changes the selected kernel

**Comment by PJ-Singh-001** [comment] 2022-11-20 01:15
Fix released in Cubic version 2022.11.73.

Please test and report any issues.

**Closed as completed by PJ-Singh-001** 2022-11-20 01:15 UTC
Labels: enhancement

**Comment by PJ-Singh-001** [comment] 2022-11-20 03:21
Also see Issue #114 [Add support for Debian](https://github.com/PJ-Singh-001/Cubic/issues/114).

**Comment by PJ-Singh-001** [comment] 2022-11-20 03:43
In the next release of Cubic (revision 73), update the list of predefined list of `squashfs` files in the constants module:

- Remove `grml64-full.squashfs` because Grml Live Linux only has one `squashfs` file so this value is not necessary.
- Leave `filesystem.squashfs` because it is generic and may be relevant for other distributions.
- Leave `ubuntu-server-minimal.squashfs` because Ubuntu Live Server 22.04 has multiple `squashfs` files.
