### ISSUE TITLE
Unable to create the customized disk image // customizing a customized image

### ISSUE THREAD

**Issue by rafe-rafe** [PJ-Singh-001/Cubic#214] opened 2023-05-18 12:30 UTC
**Describe the question**

Am actually trying to customize an already customized ubuntu20.04.1 iso image. 
In fact I started with the original version for which i made some modification and each time getting a new version as i go.
Lets say that after some wrong manipulation i need to use an older version to continue my project but after applying the new modifications I get the error "Unable to create the customized disk image".

**What you have tried**

I chose the orginial ubuntu20.04.1 iso and I did nothing to it, just went up the steps and compiled it into a new image, I used this new compiled image as the base of a new project and again I did no modification, but i got the error in the end.
It seems its not possible , for me?, to customize a customized image.
(I am using gzip option)

**OS Information (please complete the following information):**
 - work environment VirtualBox Ubuntu22.04.1

**Cubic Information (please complete the following information):**
 - Cubic Version: 2023.05.82
 - ISO Customizing: ubuntu-20.04.1-desktop-amd64

**Log from cubic**
```
Create disk image                        

  • Started process thread id.............. 140668030678592          
  • Process started by thread id........... 140668670629440                     
  • The process started at................. 16:04:50.915146                     
  • Execute asynchronously................. xorriso -as mkisofs -r -J -joliet-  
                                            long -l -iso-level 3 -V 'Ubuntu     
                                            20.04.1 2023.05.18 V1' Media        
                                            current: stdio file, overwriteable  
                                            Media status : is written , is      
                                            appendable Boot record  : El Torito 
                                            , MBR isohybrid cyl-align-off GPT   
                                            APM Media summary: 1 session,       
                                            1359209 data blocks, 2655m data,    
                                            12.8g free Volume id    : 'Ubuntu   
                                            20.04.1 V1 LTS amd64' -V 'Ubuntu    
                                            20.04.1 2023.05.18 V1' -isohybrid-  
                                            mbr --interval:local_fs:0s-         
                                            15s:zero_mbrpt,zero_gpt,zero_apm:'/h
                                            ome/ubuntu/Desktop/iso/v3/partition-
                                            1.img' -partition_cyl_align off     
                                            -partition_offset 0                 
                                            -partition_hd_cyl 166               
                                            -partition_sec_hd 32 --mbr-force-   
                                            bootable -apm-block-size 2048       
                                            -iso_mbr_part_type 0x00 -c          
                                            '/isolinux/boot.cat' -b             
                                            '/isolinux/isolinux.bin' -no-emul-  
                                            boot -boot-load-size 4 -boot-info-  
                                            table -eltorito-alt-boot -e         
                                            '/boot/grub/efi.img' -no-emul-boot  
                                            -boot-load-size 7936 -isohybrid-gpt-
                                            basdat -isohybrid-apm-hfsplus  -o "/
                                            home/ubuntu/Desktop/iso/v3/ubuntu-  
                                            20.04.1-2023.05.18-V1-desktop-      
                                            amd64.iso" .                        
  • The process id is...................... 12766                               
  • Error.................................. An exception occurred               
  • The process thread id is............... 140668030678592                     
  • The process stopped at................. 16:04:51.069390                     
  • The exit status, signal status is...... 5, None                             
  • The message is......................... xorriso 1.5.4 : RockRidge filesystem
                                            manipulator, libburnia project.     
                                            Drive current: -outdev 'stdio:/home/
                                            ubuntu/Desktop/iso/v3/ubuntu-       
                                            20.04.1-2023.05.18-V1-desktop-      
                                            amd64.iso' Media current: stdio     
                                            file, overwriteable Media status :  
                                            is blank Media summary: 0 sessions, 
                                            0 data blocks, 0 data, 5208m free   
                                            xorriso : WARNING : -volid text     
                                            problematic as automatic mount point
                                            name xorriso : WARNING : -volid text
                                            is too long for Joliet (28 > 16)    
                                            xorriso : WARNING : -volid text does
                                            not comply to ISO 9660 / ECMA 119   
                                            rules xorriso : FAILURE : Cannot    
                                            determine attributes of source file 
                                            '/home/ubuntu/Desktop/iso/v3/custom-
                                            disk/Media' : No such file or       
                                            directory xorriso : aborting :      
                                            -abort_on 'FAILURE' encountered     
                                            'FAILURE'                           
  • The exception is....................... End Of File (EOF). Exception style  
                                            platform. <pexpect.pty_spawn.spawn  
                                            object at 0x7fefe807cd90> command:  
                                            /usr/bin/xorriso args:              
                                            [b'/usr/bin/xorriso', b'-as',       
                                            b'mkisofs', b'-r', b'-J', b'-joliet-
                                            long', b'-l', b'-iso-level', b'3',  
                                            b'-V', b'Ubuntu 20.04.1 2023.05.18  
                                            V1', b'Media', b'current:',         
                                            b'stdio', b'file,',                 
                                            b'overwriteable', b'Media',         
                                            b'status', b':', b'is', b'written', 
                                            b',', b'is', b'appendable', b'Boot',
                                            b'record', b':', b'El', b'Torito',  
                                            b',', b'MBR', b'isohybrid', b'cyl-  
                                            align-off', b'GPT', b'APM',         
                                            b'Media', b'summary:', b'1',        
                                            b'session,', b'1359209', b'data',   
                                            b'blocks,', b'2655m', b'data,',     
                                            b'12.8g', b'free', b'Volume', b'id',
                                            b':', b'Ubuntu 20.04.1 V1 LTS       
                                            amd64', b'-V', b'Ubuntu 20.04.1     
                                            2023.05.18 V1', b'-isohybrid-mbr',  
                                            b'--interval:local_fs:0s-           
                                            15s:zero_mbrpt,zero_gpt,zero_apm:/ho
                                            me/ubuntu/Desktop/iso/v3/partition- 
                                            1.img', b'-partition_cyl_align',    
                                            b'off', b'-partition_offset', b'0', 
                                            b'-partition_hd_cyl', b'166',       
                                            b'-partition_sec_hd', b'32', b'--   
                                            mbr-force-bootable', b'-apm-block-  
                                            size', b'2048',                     
                                            b'-iso_mbr_part_type', b'0x00',     
                                            b'-c', b'/isolinux/boot.cat', b'-b',
                                            b'/isolinux/isolinux.bin', b'-no-   
                                            emul-boot', b'-boot-load-size',     
                                            b'4', b'-boot-info-table',          
                                            b'-eltorito-alt-boot', b'-e',       
                                            b'/boot/grub/efi.img', b'-no-emul-  
                                            boot', b'-boot-load-size', b'7936', 
                                            b'-isohybrid-gpt-basdat',           
                                            b'-isohybrid-apm-hfsplus', b'-o', b'
                                            /home/ubuntu/Desktop/iso/v3/ubuntu- 
                                            20.04.1-2023.05.18-V1-desktop-      
                                            amd64.iso', b'.'] buffer (last 100  
                                            chars): '' before (last 100 chars): 
                                            "Media' : No such file or           
                                            directory\r\nxorriso : aborting :   
                                            -abort_on 'FAILURE' encountered     
                                            'FAILURE'\r\n" after: <class        
                                            'pexpect.exceptions.EOF'> match:    
                                            None match_index: None exitstatus:  
                                            None flag_eof: True pid: 12766      
                                            child_fd: 32 closed: False timeout: 
                                            300 delimiter: <class               
                                            'pexpect.exceptions.EOF'> logfile:  
                                            None logfile_read: None             
                                            logfile_send: None maxread: 2000    
                                            ignorecase: False searchwindowsize: 
                                            None delaybeforesend: 0.05          
                                            delayafterclose: 0.1                
                                            delayafterterminate: 0.1 searcher:  
                                            searcher_re:     0: re.compile('[0- 
                                            9]{1,3}(\\.[0-9]{2}){0,1}%')        
                                            message: xorriso 1.5.4 : RockRidge  
                                            filesystem manipulator, libburnia   
                                            project.  Drive current: -outdev 'st
                                            dio:/home/ubuntu/Desktop/iso/v3/ubun
                                            tu-20.04.1-2023.05.18-V1-desktop-   
                                            amd64.iso' Media current: stdio     
                                            file, overwriteable Media status :  
                                            is blank Media summary: 0 sessions, 
                                            0 data blocks, 0 data, 5208m free   
                                            xorriso : WARNING : -volid text     
                                            problematic as automatic mount point
                                            name xorriso : WARNING : -volid text
                                            is too long for Joliet (28 > 16)    
                                            xorriso : WARNING : -volid text does
                                            not comply to ISO 9660 / ECMA 119   
                                            rules xorriso : FAILURE : Cannot    
                                            determine attributes of source file 
                                            '/home/ubuntu/Desktop/iso/v3/custom-
                                            disk/Media' : No such file or       
                                            directory xorriso : aborting :      
                                            -abort_on 'FAILURE' encountered     
                                            'FAILURE'                           
  • The trace back is...................... Traceback (most recent call last):  
                                            File "/usr/share/cubic/cubic/utiliti
                                            es/progressor.py", line 413, in     
                                            process_command     if not done:    
                                            raise exception   File "/usr/share/c
                                            ubic/cubic/utilities/progressor.py",
                                            line 408, in process_command        
                                            process.expect(PERCENT_PATTERN)     
                                            File "/usr/lib/python3/dist-        
                                            packages/pexpect/spawnbase.py", line
                                            343, in expect     return self.expec
                                            t_list(compiled_pattern_list,   File
                                            "/usr/lib/python3/dist-             
                                            packages/pexpect/spawnbase.py", line
                                            372, in expect_list     return      
                                            exp.expect_loop(timeout)   File     
                                            "/usr/lib/python3/dist-             
                                            packages/pexpect/expect.py", line   
                                            179, in expect_loop     return      
                                            self.eof(e)   File                  
                                            "/usr/lib/python3/dist-             
                                            packages/pexpect/expect.py", line   
                                            122, in eof     raise exc           
                                            pexpect.exceptions.EOF: End Of File 
                                            (EOF). Exception style platform.    
                                            <pexpect.pty_spawn.spawn object at  
                                            0x7fefe807cd90> command:            
                                            /usr/bin/xorriso args:              
                                            [b'/usr/bin/xorriso', b'-as',       
                                            b'mkisofs', b'-r', b'-J', b'-joliet-
                                            long', b'-l', b'-iso-level', b'3',  
                                            b'-V', b'Ubuntu 20.04.1 2023.05.18  
                                            V1', b'Media', b'current:',         
                                            b'stdio', b'file,',                 
                                            b'overwriteable', b'Media',         
                                            b'status', b':', b'is', b'written', 
                                            b',', b'is', b'appendable', b'Boot',
                                            b'record', b':', b'El', b'Torito',  
                                            b',', b'MBR', b'isohybrid', b'cyl-  
                                            align-off', b'GPT', b'APM',         
                                            b'Media', b'summary:', b'1',        
                                            b'session,', b'1359209', b'data',   
                                            b'blocks,', b'2655m', b'data,',     
                                            b'12.8g', b'free', b'Volume', b'id',
                                            b':', b'Ubuntu 20.04.1 V1 LTS       
                                            amd64', b'-V', b'Ubuntu 20.04.1     
                                            2023.05.18 V1', b'-isohybrid-mbr',  
                                            b'--interval:local_fs:0s-           
                                            15s:zero_mbrpt,zero_gpt,zero_apm:/ho
                                            me/ubuntu/Desktop/iso/v3/partition- 
                                            1.img', b'-partition_cyl_align',    
                                            b'off', b'-partition_offset', b'0', 
                                            b'-partition_hd_cyl', b'166',       
                                            b'-partition_sec_hd', b'32', b'--   
                                            mbr-force-bootable', b'-apm-block-  
                                            size', b'2048',                     
                                            b'-iso_mbr_part_type', b'0x00',     
                                            b'-c', b'/isolinux/boot.cat', b'-b',
                                            b'/isolinux/isolinux.bin', b'-no-   
                                            emul-boot', b'-boot-load-size',     
                                            b'4', b'-boot-info-table',          
                                            b'-eltorito-alt-boot', b'-e',       
                                            b'/boot/grub/efi.img', b'-no-emul-  
                                            boot', b'-boot-load-size', b'7936', 
                                            b'-isohybrid-gpt-basdat',           
                                            b'-isohybrid-apm-hfsplus', b'-o', b'
                                            /home/ubuntu/Desktop/iso/v3/ubuntu- 
                                            20.04.1-2023.05.18-V1-desktop-      
                                            amd64.iso', b'.'] buffer (last 100  
                                            chars): '' before (last 100 chars): 
                                            "Media' : No such file or           
                                            directory\r\nxorriso : aborting :   
                                            -abort_on 'FAILURE' encountered     
                                            'FAILURE'\r\n" after: <class        
                                            'pexpect.exceptions.EOF'> match:    
                                            None match_index: None exitstatus:  
                                            None flag_eof: True pid: 12766      
                                            child_fd: 32 closed: False timeout: 
                                            300 delimiter: <class               
                                            'pexpect.exceptions.EOF'> logfile:  
                                            None logfile_read: None             
                                            logfile_send: None maxread: 2000    
                                            ignorecase: False searchwindowsize: 
                                            None delaybeforesend: 0.05          
                                            delayafterclose: 0.1                
                                            delayafterterminate: 0.1 searcher:  
                                            searcher_re:     0: re.compile('[0- 
                                            9]{1,3}(\\.[0-9]{2}){0,1}%')        
  • Stopped process thread id.............. 140668030678592          
  • Raise the exception to thread id....... 140668670629440                     
  • Do not propagate exception............. _PyErr_SetObject: exception EOF('End
                                            Of File (EOF). Exception style      
                                            platform.\n<pexpect.pty_spawn.spawn 
                                            object at 0x7fefe807cd90>\ncommand: 
                                            /usr/bin/xorriso\nargs:             
                                            [b\'/usr/bin/xorriso\', b\'-as\',   
                                            b\'mkisofs\', b\'-r\', b\'-J\',     
                                            b\'-joliet-long\', b\'-l\', b\'-iso-
                                            level\', b\'3\', b\'-V\', b\'Ubuntu 
                                            20.04.1 2023.05.18 V1\', b\'Media\',
                                            b\'current:\', b\'stdio\',          
                                            b\'file,\', b\'overwriteable\',     
                                            b\'Media\', b\'status\', b\':\',    
                                            b\'is\', b\'written\', b\',\',      
                                            b\'is\', b\'appendable\', b\'Boot\',
                                            b\'record\', b\':\', b\'El\',       
                                            b\'Torito\', b\',\', b\'MBR\',      
                                            b\'isohybrid\', b\'cyl-align-off\', 
                                            b\'GPT\', b\'APM\', b\'Media\',     
                                            b\'summary:\', b\'1\',              
                                            b\'session,\', b\'1359209\',        
                                            b\'data\', b\'blocks,\', b\'2655m\',
                                            b\'data,\', b\'12.8g\', b\'free\',  
                                            b\'Volume\', b\'id\', b\':\',       
                                            b\'Ubuntu 20.04.1 V1 LTS amd64\',   
                                            b\'-V\', b\'Ubuntu 20.04.1          
                                            2023.05.18 V1\', b\'-isohybrid-     
                                            mbr\', b\'--interval:local_fs:0s-   
                                            15s:zero_mbrpt,zero_gpt,zero_apm:/ho
                                            me/ubuntu/Desktop/iso/v3/partition- 
                                            1.img\', b\'-partition_cyl_align\', 
                                            b\'off\', b\'-partition_offset\',   
                                            b\'0\', b\'-partition_hd_cyl\',     
                                            b\'166\', b\'-partition_sec_hd\',   
                                            b\'32\', b\'--mbr-force-bootable\', 
                                            b\'-apm-block-size\', b\'2048\',    
                                            b\'-iso_mbr_part_type\', b\'0x00\', 
                                            b\'-c\', b\'/isolinux/boot.cat\',   
                                            b\'-b\',                            
                                            b\'/isolinux/isolinux.bin\', b\'-no-
                                            emul-boot\', b\'-boot-load-size\',  
                                            b\'4\', b\'-boot-info-table\',      
                                            b\'-eltorito-alt-boot\', b\'-e\',   
                                            b\'/boot/grub/efi.img\', b\'-no-    
                                            emul-boot\', b\'-boot-load-size\',  
                                            b\'7936\', b\'-isohybrid-gpt-       
                                            basdat\', b\'-isohybrid-apm-        
                                            hfsplus\', b\'-o\', b\'/home/ubuntu/
                                            Desktop/iso/v3/ubuntu-20.04.1-      
                                            2023.05.18-V1-desktop-amd64.iso\',  
                                            b\'.\']\nbuffer (last 100 chars):   
                                            \'\'\nbefore (last 100 chars):      
                                            "Media\' : No such file or          
                                            directory\\r\\nxorriso : aborting : 
                                            -abort_on \'FAILURE\' encountered   
                                            \'FAILURE\'\\r\\n"\nafter: <class   
                                            \'pexpect.exceptions.EOF\'>\nmatch: 
                                            None\nmatch_index: None\nexitstatus:
                                            None\nflag_eof: True\npid:          
                                            12766\nchild_fd: 32\nclosed:        
                                            False\ntimeout: 300\ndelimiter:     
                                            <class \'pexpect.exceptions.EOF\'>\n
                                            logfile: None\nlogfile_read:        
                                            None\nlogfile_send: None\nmaxread:  
                                            2000\nignorecase:                   
                                            False\nsearchwindowsize:            
                                            None\ndelaybeforesend:              
                                            0.05\ndelayafterclose:              
                                            0.1\ndelayafterterminate:           
                                            0.1\nsearcher: searcher_re:\n    0: 
                                            re.compile(\'[0-9]{1,3}(\\\\.[0-    
                                            9]{2}){0,1}%\')\nmessage: xorriso   
                                            1.5.4 : RockRidge filesystem        
                                            manipulator, libburnia              
                                            project.\n\nDrive current: -outdev \
                                            'stdio:/home/ubuntu/Desktop/iso/v3/u
                                            buntu-20.04.1-2023.05.18-V1-desktop-
                                            amd64.iso\'\nMedia current: stdio   
                                            file, overwriteable\nMedia status : 
                                            is blank\nMedia summary: 0 sessions,
                                            0 data blocks, 0 data, 5208m        
                                            free\nxorriso : WARNING : -volid    
                                            text problematic as automatic mount 
                                            point name\nxorriso : WARNING :     
                                            -volid text is too long for Joliet  
                                            (28 > 16)\nxorriso : WARNING :      
                                            -volid text does not comply to ISO  
                                            9660 / ECMA 119 rules\nxorriso :    
                                            FAILURE : Cannot determine          
                                            attributes of source file \'/home/ub
                                            untu/Desktop/iso/v3/custom-         
                                            disk/Media\' : No such file or      
                                            directory\nxorriso : aborting :     
                                            -abort_on \'FAILURE\' encountered   
                                            \'FAILURE\'') is not a BaseException
                                            subclass  
```

**Comment by mirek190** [comment] 2023-05-18 21:55
I also experienced that with the newest cubic version.

**Comment by PJ-Singh-001** [comment] 2023-05-18 23:30
You should be able to customize a previously customized ISO.
Thanks for including the original ISO information and the error log.
I will look into this.

**Comment by PJ-Singh-001** [comment] 2023-05-23 13:46
I did the following test...
1. I generated customized an ISO in Cubic.
2. Then I created a new Cubic project.
3. I selected the customized ISO from step 2, to customize in Cubic
4. I was able to successfully customize the previously customized ISO.

So, yes, you can customize a previously customized ISO using Cubic.
(Cubic was designed to allow this, but I wanted to verify there was no bug).

---

From your log output, I see that you are creating a new ISO:

    `/home/ubuntu/Desktop/iso/v3/ubuntu-20.04.1-2023.05.18-V1-desktop-amd64.iso" .` in Virtualbox.

I also see the following error:

    FAILURE : Cannot determine attributes of source file '/home/ubuntu/Desktop/iso/v3/custom-disk/Media' : No such file or directory xorriso

What is `.../custom-disk/Media`?

Each Cubic project has a very specific structure. It looks similar to this:

    <your Cubic project>
    ├── custom-disk
    │   ├── boot
    │   ├── casper
    │   ├── dists
    │   ├── EFI
    │   ├── install
    │   ├── isolinux
    │   ├── md5sum.txt
    │   ├── pics
    │   ├── pool
    │   ├── preseed
    │   ├── README.diskdefines
    │   └── ubuntu -> .
    ├── custom-root
    ├── partition-1.img
    ├── partition-2.img
    ├── source-disk
    ├── <your customized iso name>.iso
    └── <your customized iso name>.md5

You should not have any other files or directories in this project folder.

It looks like you've created a folder named `Media` inside `/home/ubuntu/Desktop/iso/v3/custom-disk/custom-disk/`. I guess your intention is to have this folder and it's contents copied to the generated ISO. Theoretically this should work. However, there may be issues if `Media` is a symlink to something that does not exist, or if it is corrupted in some way.

You should try deleting `/home/ubuntu/Desktop/iso/v3/custom-disk/Media` to see if that solves your problem.

**Comment by rafe-rafe** [comment] 2023-05-23 14:48
Thx for your response.
Its very weird, i have no idea what this folder is about and why it exsists, I didn't modify anything at all.
I loaded the base ubuntu20.04 and i compiled it  with cubic without modifying anything, I did the same on the newly compiled one and i got this error.

I will try it again...

**Comment by PJ-Singh-001** [comment] 2023-05-23 16:08
Ok. Let me know how it works.

The folder may have been in the original (customized) ISO that you are trying to customize, because Cubic just extracts the contents of the original ISO.

(By the way, use Cubic version 2023.05.83, which I just released last night).

If you still have the problem, cut and paste the contents of…

    /home/ubuntu/Desktop/iso/v3/cubic.conf

….so I can see information about your project.

**Comment by rafe-rafe** [comment] 2023-06-04 13:59
Hello,

I could try all the steps I did previously, compiling and trying after each step, and it seems to work perfectly.
It's weird that I'm not getting this error anymore. It might be because I switched versions of cubic midway? (2023.04.81->2023.05.82) 
Either way, I'm glad it's working for me now, and thank you for your time.

**Comment by lisymail** [comment] 2024-07-23 03:36
how resolve it?

**Comment by PJ-Singh-001** [comment] 2024-07-25 00:20
@lisymail,

I'm closing this issue because @ramitfeghali solved their problem.

You should open a new issue. Include all details of your error, and include the log output in your new issue.

**Closed as completed by PJ-Singh-001** 2024-07-25 00:20 UTC
Labels: question
