### ISSUE TITLE
Error during the Analyze step on the Extract page for Linux Mint 20.3.

### ISSUE THREAD

**Issue by fg-dev** [PJ-Singh-001/Cubic#27] opened 2022-02-16 08:28 UTC
**Describe the bug**
I used cubic with Linux mint 20.3, but cubic says that It can not recognize the disk information

**Cubic Information (please complete the following information):**
 - Cubic Version: latest
 - ISO Customizing: linuxmint-20.3-cinnamon-64bit.iso

**Screenshots**
![Screenshot from 2022-02-16 1109-21-13](https://user-images.githubusercontent.com/7328388/154225209-73d74641-ca3c-4680-9d8c-794c05a153cf.png)

**Comment by PJ-Singh-001** [comment] 2022-02-16 16:01
Are you sure your original ISO file is not corrupt?

I am not able to reproduce this issue with `linuxmint-20.3-cinnamon-64bit.iso`...

![Screenshot from 2022-02-16 10-56-28](https://user-images.githubusercontent.com/19394936/154305196-7f814299-4f61-478b-a4ea-a2475554803b.png)

![Screenshot from 2022-02-16 10-57-43](https://user-images.githubusercontent.com/19394936/154305216-824e9c78-c34c-4190-9084-42c4d8ecd337.png)

After you check your ISO, if you are still experiencing this issue, please run cubic using the command `cubic --verbose`. Then cut and paste the log output here.

**Comment by PJ-Singh-001** [comment] 2022-02-21 00:33
fg-dev,

I am closing this issue.
If you are still experiencing the problem, please attach the logs, and feel free to reopen the issue.

**Closed as completed** 2022-02-21 00:33 UTC
Labels: invalid
