### ISSUE TITLE
Extract Ubuntu 23.04 (Lunar) ISO image fails.

### ISSUE THREAD

**Issue by rarnu** [PJ-Singh-001/Cubic#151] opened 2023-01-23 09:14 UTC
I tried to customize the image for Ubuntu 23.04(lunar), but it failed during the extract step. 
The error message is "Unable to locate the compressed Linux file system." .

ISO is downloaded here: https://cdimage.ubuntu.com/daily-live/20230123/lunar-desktop-amd64.iso
And some logs:
```
Extract image from..................... /home/rarnu/Downloads/lunar-desktop-
                                            amd64-2.iso                         
  • Extract image to....................... /home/rarnu/iscos/partition-2.img   
  • Extract image blocks................... block size: 512, skip blocks:       
                                            10561072, block count: 8504         
  • Execute synchronously.................. dd if="/home/rarnu/Downloads/lunar- 
                                            desktop-amd64-2.iso" bs="512"       
                                            skip="10561072" count="8504" of="/ho
                                            me/rarnu/iscos/partition-2.img"     
  • The process id is...................... 9912                                
  • The result is.......................... 8504+0 records in  8504+0 records   
                                            out  4354048 bytes (4.4 MB, 4.2 MiB)
                                            copied, 0.0296954 s, 147 MB/s       
  • The exit status, signal status is...... 0, None                             
  • The interval path is................... -append_partition 2                 
                                            28732ac11ff8d211ba4b00a0c93ec93b --i
                                            nterval:local_fs:0d-                
                                            8503d::'{boot_image_directory}/parti
                                            tion-2.img'                         
  • The interval path is................... -e '--interval:appended_partition_2_
                                            start_2640268s_size_8504d:all::'    
  • The interval path is................... -e '--                              
                                            interval:appended_partition_2:all::'
  • Set status iso template................ 789C8D51CD8E832010BEFB14DCBCEC54456B
                                            AD0FB25732C06848500CD0266DD3775F6CDD
                                            A69B6CB27B80C03730DFCFC027CB6F67674F
                                            1309A3EF790630FA93E43049CF00CC1CC99F
                                            D1F6D629B462087D19A0DA87FE4ADE89F466
                                            891F8FE3B8C43EBF49E7A230138E24B4F1A4
                                            A2F3977BB1A08F261A3743B533D3B8722CDE
                                            C554366782296817C0A2249BC1EBA950172B
                                            D09A71666E18DE0BE91A28B2AA4D6D920018
                                            9C57042B334A4B19E0B2D0ACC5EB03E38C77
                                            879AA3AAAA61E834AF2A898D2C4B2CD5B1A6
                                            B4E4EF463574FBB2D6FD3F7CF1CDD7939B9E
                                            EC02C31A4B06263CA27A82F1B210438EA52E
                                            49D25E1EEBBA69BA832ADB4EB6F2C0DBE351
                                            1D32502C2F56D69DC288D6ADCDE50615EB80
                                            0A53772D2CAA209BC498E83605B3039A4EF6
                                            9147F6D8C13AD410CC9558B321661E1C6C71
                                            6DE37EE1197C7704B471EB432C7F8BE887CB
                                            E750788FD6A6A4FE1090026DB22F4474D7FA

  Find the compressed Linux file system    

  • Search for file name pattern........... .*\.squashfs$                       
  • In directory........................... /home/rarnu/iscos/source-disk       
  • Matched file........................... casper/minimal.squashfs             
  • Matched file........................... casper/minimal.de.squashfs          
  • Matched file........................... casper/minimal.en.squashfs          
  • Matched file........................... casper/minimal.es.squashfs          
  • Matched file........................... casper/minimal.fr.squashfs          
  • Matched file........................... casper/minimal.it.squashfs          
  • Matched file........................... casper/minimal.no-languages.squashfs
  • Matched file........................... casper/minimal.pt.squashfs          
  • Matched file........................... casper/minimal.ru.squashfs          
  • Matched file........................... casper/minimal.standard.squashfs    
  • Matched file........................... casper/minimal.standard.de.squashfs 
  • Matched file........................... casper/minimal.standard.en.squashfs 
  • Matched file........................... casper/minimal.standard.es.squashfs 
  • Matched file........................... casper/minimal.standard.fr.squashfs 
  • Matched file........................... casper/minimal.standard.it.squashfs 
  • Matched file........................... casper/minimal.standard.live.squashf
                                            s                                   
  • Matched file........................... casper/minimal.standard.no-         
                                            languages.squashfs                  
  • Matched file........................... casper/minimal.standard.pt.squashfs 
  • Matched file........................... casper/minimal.standard.ru.squashfs 
  • Matched file........................... casper/minimal.standard.zh.squashfs 
  • Matched file........................... casper/minimal.zh.squashfs          
  • Ignore recursive directory............. /home/rarnu/iscos/source-disk/ubuntu
  • The squashfs file paths are............ ['casper/minimal.squashfs',         
                                            'casper/minimal.de.squashfs',       
                                            'casper/minimal.en.squashfs',       
                                            'casper/minimal.es.squashfs',       
                                            'casper/minimal.fr.squashfs',       
                                            'casper/minimal.it.squashfs',       
                                            'casper/minimal.no-                 
                                            languages.squashfs',                
                                            'casper/minimal.pt.squashfs',       
                                            'casper/minimal.ru.squashfs',       
                                            'casper/minimal.standard.squashfs', 
                                            'casper/minimal.standard.de.squashfs
                                            ', 'casper/minimal.standard.en.squas
                                            hfs', 'casper/minimal.standard.es.sq
                                            uashfs', 'casper/minimal.standard.fr
                                            .squashfs', 'casper/minimal.standard
                                            .it.squashfs', 'casper/minimal.stand
                                            ard.live.squashfs',                 
                                            'casper/minimal.standard.no-        
                                            languages.squashfs', 'casper/minimal
                                            .standard.pt.squashfs', 'casper/mini
                                            mal.standard.ru.squashfs', 'casper/m
                                            inimal.standard.zh.squashfs',       
                                            'casper/minimal.zh.squashfs']       
  • Error.................................. Unable to locate the squashfs file  
                                            path                                
```

**Comment by PJ-Singh-001** [comment] 2023-02-01 00:40
Confirmed using `lunar-desktop-amd64.iso` (Daily build from 2023-01-31 08:14) from [Ubuntu 23.04 (Lunar Lobster) Daily Build](https://cdimage.ubuntu.com/daily-live).

This is scary!... Looks like Canonical have completely changed the layout of the ISO (unless this is collection of `squashfs` files is temporary?)...

    minimal.de.squashfs
    minimal.en.squashfs
    minimal.es.squashfs
    minimal.fr.squashfs
    minimal.it.squashfs
    minimal.no-languages.squashfs
    minimal.pt.squashfs
    minimal.ru.squashfs
    minimal.squashfs
    minimal.standard.de.squashfs
    minimal.standard.en.squashfs
    minimal.standard.es.squashfs
    minimal.standard.fr.squashfs
    minimal.standard.it.squashfs
    minimal.standard.live.squashfs
    minimal.standard.no-languages.squashfs
    minimal.standard.pt.squashfs
    minimal.standard.ru.squashfs
    minimal.standard.squashfs
    minimal.standard.zh.squashfs
    minimal.zh.squashfs

Let's wait a little bit to see if they settle on the traditional *single* `*.squashfs` file.

**Comment by cfroystad** [comment] 2023-02-08 10:37
If I recall correctly, they're changing the Desktop variant to align with the changes already made in the server for 22.04.
At least they're using the same [installer framework](https://github.com/canonical/subiquity)

**Comment by PJ-Singh-001** [comment] 2023-02-10 20:39
Ok.
Thanks for the info.
Cubic does not work with the server installer.
(I suspected they may eventually introduce this to the desktop ISO as well).

**Comment by danimesq** [comment] 2023-03-03 02:33
Moved https://bugs.launchpad.net/cubic/+bug/2008949 to this issue here.

**Comment by danimesq** [comment] 2023-03-04 20:19
I've used an Ubuntu 23 build from December and it had two squashfs files in the project folder, but did worked anyway.

However a March 1 build had the same error as OP and as I've reported in launchpad

**Comment by PJ-Singh-001** [comment] 2023-03-05 14:50
Referencing https://bugs.launchpad.net/cubic/+bug/2008949:

> Related issue to older versions of Ubuntu that weren't immediately supported by Cubic: https://answers.launchpad.net/cubic/+question/699265
>
> December 2022's build of Ubuntu 23 (that didn't added the new Flutter installer yet - I'm not saying this is related) did worked, unlike when I tried today's (03/01/2023) daily build.

> CLI ('ubiquity --verbose)' log says:
>
> ```(cubic:48456): Gtk-WARNING **: 19:59:46.405: Failed to measure available space: Error getting filesystem info for /media/daniella/ceb6a175-7104-43d8-8064-48e6ef72cd27/fourluna/source-disk: No such file or directory```

**Comment by danimesq** [comment] 2023-03-05 17:06
Do you think `(cubic:48456): Gtk-WARNING **: 19:59:46.405: Failed to measure available space: Error getting filesystem info for /media/daniella/ceb6a175-7104-43d8-8064-48e6ef72cd27/fourluna/source-disk: No such file or directory` may give a glue to fix this?

**Comment by PJ-Singh-001** [comment] 2023-03-06 00:30
I think it has to to with the new structure of the ISO. This may be a symptom of that.

**Comment by danimesq** [comment] 2023-03-06 01:21
May Ubuntu keep this structure on Ubuntu 23's launch? If so, are there some ideas to fix that on Cubic's side?

**Comment by PJ-Singh-001** [comment] 2023-03-06 18:46
Right now, I don’t know how to handle the newer Ubuntu Server ISOs, and I think the 23.04 Desktop ISO is going to use the same structure.

I suspect that Cubic will not work with 23.04. Of course I would like to make it work, but there is no documentation on how Canonical creates the new ISOs, so it is hard to reverse engineer.

**Comment by danimesq** [comment] 2023-03-06 20:51
I dunno if this may be helpful, anyway here's a 5 cents that may give a clue: https://askubuntu.com/questions/1404757/create-custom-ubuntu-22-04-live-server-iso

**Comment by danimesq** [comment] 2023-03-06 20:55
And, hopefully, as [this page](https://help.ubuntu.com/community/LiveCDCustomization) is updated about Ubuntu 22, soon after April it may be updated to reflect the Ubuntu 23's new ISO structure; so it's on the watch list.

**Comment by PJ-Singh-001** [comment] 2023-03-07 20:07
Thanks for sharing these links!

**Comment by PJ-Singh-001** [comment] 2023-03-13 02:22
In order to customize Ubuntu 23.04 (Lunar Lobster), you will need to install Cubic version 2023.03.77.

Update cubic using:

    sudo apt update
    sudo apt install cubic

1. **Project page**

    Select the 23.04 ISO to customize.

    Update parameters, as desired.

 2. **Terminal page**

    Install Ubiquity because the new Flutter based Ubuntu Desktop Installer is not available in the Linux file system being customized in Cubic.

        apt update
        apt install ubiquity ubiquity-casper ubiquity-frontend-gtk ubiquity-slideshow-ubuntu ubiquity-ubuntu-artwork

    Ignore errors or warnings about `cryptsetup`, `update-initramfs`, and `initramfs-tools`.

3. **Packages page**

    Turn off the "＋Minimal" switch in the header bar, so only the "Typical" column is visible.

    Click in the list of packages, and start typing "ubiquity" to search for `ubiquity` packages.

    Check mark the following packages to automatically remove them after installation, since we only need Ubiquity in the Live environment.

    - `ubiquity`
    - `ubiquity-casper`
    - `ubiquity-frontend-gtk`
    - `ubiquity-slideshow-ubuntu`
    - `ubiquity-ubuntu-artwork`

4. **Options page, Kernel tab**

    Select kernel 6.1.0-16, with the following files. (This will be the last item at the bottom of the list, with the description "This kernel is used to bootstrap the original disk...").

        vmlinuz
        initrd

    _This is important!_ If you do not do this, you will get a "not syching to kernel" error when booting your custom ISO. Note that you must make this selection each time you customize your project, because Cubic defaults to the newest kernel available inside the `/boot` directory of the Linux file system.

 5. **Install Ubuntu 23.04**

    When you boot into the Customized Live ISO, click the <kbd>Install Ubuntu</kbd> button, to install Ubuntu.

    If you click the <kbd>Try Ubuntu</kbd> button, you will need to enter user information in the Welcome wizard. In this case, the Ubiquity launcher in the Dash will not work. Instead, open a terminal, type `ubiquity`, press <kbd>Enter</kbd>, and you will be prompted to enter the user's sudo password to proceed.

**Comment by PJ-Singh-001** [comment] 2023-03-13 02:36
Fix released in Cubic version 2023.03.77.

Be sure to follow the [above instructions](https://github.com/PJ-Singh-001/Cubic/issues/151#issuecomment-1465411943) when Customizing Ubuntu 23.04 (Lunar Lobster).

**Closed as completed by PJ-Singh-001** 2023-03-13 02:36 UTC
Labels: bug

**Comment by rarnu** [comment] 2023-03-13 10:49
Thanks for your great work !

**Comment by danimesq** [comment] 2023-03-13 20:41
About steps:

2: how to install Ubuntu 23's Subiquity (Flutter) instead of the classic Ubiquity?

3: will a future update from Cubic do the minimal package selection automatically? probably not required as there will be a better fix where user won't need to manually install Ubiquity.

4: what possibly is the bug preventing from installing an newer kernel version?

5: will the user manually installing the Flutter Ubiquity from apt fix this issue?

**Comment by PJ-Singh-001** [comment] 2023-03-13 23:19
> 2: how to install Ubuntu 23's Subiquity (Flutter) instead of the classic Ubiquity?

You could theoretically use any installer.

However, the new Flutter based installer is a Snap App, and we can not install Snaps in Cubic's [Terminal environment](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page). ([See this Snappy bug report](https://bugs.launchpad.net/snappy/+bug/1609903)).

> 3: will a future update from Cubic do the minimal package selection automatically? probably not required as there will be a better fix where user won't need to manually install Ubiquity.

With 23.04, you are only able to customize the minimal version of Ubuntu in Cubic 2023.03.77, anyway. As a result, the installer no longer needs to remove (unneeded) packages that were present in the Live ISO environment. This is the structural change they made to the ISO, and it is more efficient to do an install this way. (The [Packages page](https://github.com/PJ-Singh-001/Cubic/wiki/Packages-Page) in Cubic exists to configure this feature of Ubiquity, and if Ubiquity is not installed, this page is not shown).

> 4: what possibly is the bug preventing from installing an newer kernel version?

You can install a newer kernel version. This version will be available when you install your system. So feel free to install a new kernel; just make sure you still select the original kernel to _bootstrap your ISO_, per the instructions above.

I have not been able to create an `initrd` with an updated kernel that can successfully boot the Live environment from the ISO. (I'm sure some users who are more advanced may be able to do it; the changes would be done inside the [Terminal environment](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page) and are not something Cubic would handle for the user).

In lieu of creating your own `initrd` you can use the original kernel that came with the ISO to bootstrap it. _Remember, Cubic's [Kernel tab](https://github.com/PJ-Singh-001/Cubic/wiki/Options-Page#kernel-tab) is only used to select the bootstrap kernel for the Live ISO_.

Thus, you can update the kernel while you are customizing the Linux file system; just realize, you won't be able to interact with that kernel until after you have install your customized ISO to a computer.

> 5: will the user manually installing the Flutter Ubiquity from apt fix this issue?

I did not find an `apt` package for the Flutter Ubuntu Installer. If you find that, you can install it instead of Ubiquity. However, I think you may need to figure out how to remove the package(s) once the OS is installed. (Obviously, you wouldn't want someone to click on this App on an installed system, and damage their working system).

---

The next release of Cubic will _reintroduce_ the "overlay" squashfs files, including the one that contains the Flutter Ubuntu Installer. You will not be able to update/or upgrade the Installer App, but your customized ISO will be able to use it to install your Customized OS. Then you will not need the [temporary workaround above](https://github.com/PJ-Singh-001/Cubic/issues/151#issuecomment-1465411943).

**Comment by PJ-Singh-001** [comment] 2023-03-17 23:40
Please see [Add additional support for Ubuntu 23.04 Lunar Lobster](https://github.com/PJ-Singh-001/Cubic/issues/172), Issue #172.

Cubic version 2023.03-78 reintroduces the "overlay" squashfs files, so the Flutter Ubuntu Installer will now work.
