### ISSUE TITLE
Apt does not work when customizing Ubuntu 22.04 with Cubic in Ubuntu 18.04.

### ISSUE THREAD

**Issue by stj0nes** [PJ-Singh-001/Cubic#67] opened 2022-06-08 13:33 UTC
Re-open of issue #63 

Describe the bug

When I try to use any apt commands in the virtual environment terminal and a 22.04 ISO file, I'm met with a "problem executing scripts" error message. Due to this, I'm unable to remove or install packages & dependencies using apt. Dpkg command works fine if dependent packages are already installed.

If I use that same ISO file to create a VM, apt commands all work normally. Maybe something has changed with 22.04 that causes Cubic's virtual environment to have issues or maybe I'm using an out of date version of Cubic? Customizing 18.04 & 20.04 ISO files works without an issue with the version that I have.

To Reproduce

Open Cubic to the virtual environment terminal with a 22.04 ISO file and try to run apt update, apt install, apt purge commands.

Expected behavior

Apt commands would work normally in the virtual environment to install/remove various packages.

OS Information (please complete the following information):

OS/Distro Name: Ubuntu
OS Version: 22.04
Cubic Information (please complete the following information):

Cubic Version: 2022.01.70
ISO Customizing: ubuntu-22.04-desktop-amd64.iso
Download Link: https://ubuntu.com/download/desktop
Cubic Log:

No log provided by cubic.

Screenshots

No screenshots applicable, see attached text file of a brand new project using the default sources.list file included in the ISO and no 3rd party PPAs being used.
[jammyError1.txt](https://github.com/PJ-Singh-001/Cubic/files/8861845/jammyError1.txt)

**Comment by PJ-Singh-001** [comment] 2022-06-09 03:32
I am not getting this issue when creating a brand new Cubic project using `ubuntu-22.04-desktop-amd64.iso`...

    You have entered the virtual environment.
    root@cubic:~# apt update
    Get:1 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
    Get:2 http://archive.ubuntu.com/ubuntu jammy InRelease [270 kB]     
    Get:3 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [109 kB]
    Get:4 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [159 kB]
    Get:5 http://archive.ubuntu.com/ubuntu jammy/main amd64 DEP-11 Metadata [423 kB]
    Get:6 http://security.ubuntu.com/ubuntu jammy-security/main Translation-en [39.2 kB] 
    Get:7 http://security.ubuntu.com/ubuntu jammy-security/main amd64 DEP-11 Metadata [11.4 kB]
    Get:8 http://security.ubuntu.com/ubuntu jammy-security/main DEP-11 48x48 Icons [5952 B]                     
    Get:9 http://security.ubuntu.com/ubuntu jammy-security/main DEP-11 64x64 Icons [8219 B]     
    Get:10 http://security.ubuntu.com/ubuntu jammy-security/main DEP-11 64x64@2 Icons [29 B]                  
    Get:11 http://security.ubuntu.com/ubuntu jammy-security/main amd64 c-n-f Metadata [2600 B]    
    Get:12 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [148 kB]    
    Get:13 http://security.ubuntu.com/ubuntu jammy-security/restricted Translation-en [22.4 kB]              
    Get:14 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 c-n-f Metadata [464 B]
    Get:15 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [277 kB]
    Get:16 http://archive.ubuntu.com/ubuntu jammy-updates/main Translation-en [68.2 kB]
    Get:17 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 DEP-11 Metadata [73.4 kB]
    Get:18 http://archive.ubuntu.com/ubuntu jammy-updates/main DEP-11 48x48 Icons [25.0 kB]
    Get:19 http://archive.ubuntu.com/ubuntu jammy-updates/main DEP-11 64x64 Icons [37.1 kB]
    Get:20 http://archive.ubuntu.com/ubuntu jammy-updates/main DEP-11 64x64@2 Icons [29 B]
    Get:21 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 c-n-f Metadata [4840 B]
    Get:22 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [165 kB]
    Get:23 http://archive.ubuntu.com/ubuntu jammy-updates/restricted Translation-en [25.0 kB]
    Get:24 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 c-n-f Metadata [460 B]
    Fetched 1986 kB in 1s (2969 kB/s)                                          
    Reading package lists... Done
    Building dependency tree... Done
    Reading state information... Done
    223 packages can be upgraded. Run 'apt list --upgradable' to see them.
    root@cubic:~# 
    root@cubic:~# apt --fix-broken install
    Reading package lists... Done
    Building dependency tree... Done
    Reading state information... Done
    0 upgraded, 0 newly installed, 0 to remove and 223 not upgraded.

In your console output, I see two interesting errors...

    E: Problem executing scripts APT::Update::Post-Invoke-Success 'touch /var/lib/apt/periodic/update-success-stamp 2>/dev/null || true'
    E: Sub-process returned an error code

...and...

    E: Problem executing scripts APT::Install::Pre-Invoke '[ ! -f /usr/lib/ubuntu-advantage/apt-esm-hook ] || /usr/lib/ubuntu-advantage/apt-esm-hook pre-invoke || true'
    E: Sub-process returned an error code

It looks like `apt` is having a problem executing this script

    /usr/lib/ubuntu-advantage/apt-esm-hook

In Cubic, what happens when you try to execute this script manually? (To run the script cut-and-paste the following and presse <kbd>Enter</kbd>).

    /usr/lib/ubuntu-advantage/apt-esm-hook

Also, what is the output of?...

    apt-add-repository --list

**Comment by stj0nes** [comment] 2022-06-09 12:25
I've been beating my head against the wall trying to figure out those apt error messages, at first I thought it was my network blocking something but every network connection that I've tried gives the same messages and I can ping the sites without a problem. I can't seem to find any log files to point me in some sort of direction either.

If I run the `apt-esm-hook` manually, nothing seems to happen, don't get any errors or messages of any kind.

Output of `apt-add-repository --list` gives me:

    deb http://archive.ubuntu.com/ubuntu/ jammy restricted main
    deb http://security.ubuntu.com/ubuntu/ jammy-security restricted main
    deb http://archive.ubuntu.com/ubuntu/ jammy-updates restricted main

**Comment by PJ-Singh-001** [comment] 2022-06-10 01:23
Try disabling this ubuntu-advantage script by moving the config file somewhere else, so it is not invoked...

    mv /etc/apt/apt.conf.d/20apt-esm-hook.conf ~/

(I suspect there is some other problem, but let's see what happens).

**Comment by stj0nes** [comment] 2022-06-15 16:07
Okay, moved the apt-esm-hook conf file and no change for the error messages.

**Comment by PJ-Singh-001** [comment] 2022-06-17 02:07
Looking at [your comment on June 9th above](https://github.com/PJ-Singh-001/Cubic/issues/67#issuecomment-1151056132) may be you are missing the `universe` repository?

    apt-add-repository universe

**Comment by stj0nes** [comment] 2022-06-17 13:13
No luck after adding the universe repository, same error messages persist.

**Comment by PJ-Singh-001** [comment] 2022-06-18 00:49
Do you use Ubuntu Advantage on your host machine?

**Comment by stj0nes** [comment] 2022-06-18 13:24
I do yes, could that be possibly causing an issue with Cubic?

**Comment by PJ-Singh-001** [comment] 2022-06-21 20:50
This is the only theory I can suggest, especially since your error specifically refers to Ubuntu Advantage.

    E: Problem executing scripts APT::Install::Pre-Invoke '[ ! -f /usr/lib/ubuntu-advantage/apt-esm-hook ] || /usr/lib/ubuntu-advantage/apt-esm-hook pre-invoke || true'
    E: Sub-process returned an error code

The [Terminal environment](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page) in Cubic is a container, that isolates/protects your host system form any changes you make to the file system your are customizing.

Although it fully virtualizes the file system hierarchy, the process tree, the various IPC subsystems and the host and domain name, it still does use the IP address of the host machine.

May be there is something about the implementation of Ubuntu Advantage that interferes with this kind of setup. (Perhaps it is by design, to prevent organizations from using Ubuntu Advantage with multiple containers without paying for the enterprise license???).

If you install and run Cubic inside a virtual machine, you may be able to sidestep this issue.

**Comment by stj0nes** [comment] 2022-06-22 15:43
I was wondering if Ubuntu Advantage was causing some issues, from what I can tell Ubuntu includes the Advantage toolset as default in the OS so I didn't think that would be causing problems but maybe they changed how it functions in 22.04?

I went and created an 18.04 virtual machine and installed Cubic, still get the same error messages that I've been getting on my laptop which also runs 18.04 for it's host OS.

On a whim, I created a 20.04 virtual machine and installed Cubic to give a shot at customizing 22.04. To my surprise, Cubic had no problem with apt scripts and I can do everything normally there that was erroring with Cubic on 18.04. 

I'm thinking that there is something between 18.04 and 22.04 that isn't playing nice somewhere along the way, probably something got moved somewhere else within the OS by Canonical that the script(s) are trying to call.

**Comment by PJ-Singh-001** [comment] 2022-06-23 23:31
Are you using an updated Ubuntu 18.04 Bionic ?

Cubic only works with Ubuntu 18.04.5 Bionic (note the **.5**) and above.
This is because some of the packages Cubic needs have bugs, or are simply not available, in versions of Ubuntu < 18.04.5.

**Comment by stj0nes** [comment] 2022-06-24 11:37
I am yes, both my laptop and the VM I created are using the 18.04.6 ISO file from Ubuntu's download page

**Comment by PJ-Singh-001** [comment] 2022-06-25 01:04
I downloaded [Ubuntu 18.04.6](https://releases.ubuntu.com/18.04.6/ubuntu-18.04.6-desktop-amd64.iso).

I booted it into VirtualBox. Then I installed Cubic, and I attempted to customize the [Ubuntu 18.04.6 ISO](https://releases.ubuntu.com/18.04.6/ubuntu-18.04.6-desktop-amd64.iso).

As you can see, I do not have an issue running `apt` commands in Cubic.

![image](https://user-images.githubusercontent.com/19394936/175752325-fd64ccd7-8c37-43f1-872d-0006533e33d1.png)

**Comment by stj0nes** [comment] 2022-06-27 13:20
Right, so customizing Ubuntu 18.04 & 20.04 ISO files works fine with Cubic on a host system running both of those OS levels. The issue that I'm running into is that a host 18.04 can't handle 22.04 ISO files for whatever reason.

I am using VMware Workstation Pro on a corporate issued system for this so maybe that's coming into play? The VMs don't have the security software installed so that's not coming into play and when I try off the corporate network to rule that out, I get the same messages. 

18.04 VM screenshot:
![Cubic_Error](https://user-images.githubusercontent.com/106770184/175942637-c6f4d280-091c-4351-aca7-178c02bc2ec5.png)

20.04 VM screenshot:
![Focal_2004](https://user-images.githubusercontent.com/106770184/175942685-a6460ec3-fc2a-414e-86f4-18651e996cda.png)

**Comment by PJ-Singh-001** [comment] 2022-06-27 15:40
I see...
I'll try that combination: 18.04.6 host and customizing 20.04 iso.

Cubic always uses the host machines current kernel (and there is no way around that).
This kernel is displayed at the top right of the Terminal page.
Perhaps that is contributing to the issue you are experiencing?

**Comment by PJ-Singh-001** [comment] 2022-06-27 17:08
I am getting the same result now.
Apt does not work when the host machine is running 18.04.6 and the ISO being customized is 22.04.

In the past, I have been able to customize a newer ISO while running an older OS on the host machine.

Now that I can reproduce your issue, I'll see if I can come up with a work-around or solution.

![image](https://user-images.githubusercontent.com/19394936/175996248-0be28040-fec9-43c3-b48b-d6452bfdcec3.png)

**Comment by PJ-Singh-001** [comment] 2022-07-30 23:05
Closing this issue with the above solution provided.

**Comment by PJ-Singh-001** [comment] 2022-12-08 01:52
As a work-around, install and run Cubic in newer OS than 18.04 (using a virtual machine such as Virtual Box) when customizing Ubuntu based distributions >=20.04.

**Comment by PJ-Singh-001** [comment] 2023-03-26 19:12
The following work-around allows you to customize Ubuntu 22.04 from Cubic running in Ubuntu 18.04.

The only drawback is that you will not be able to create a newer `initrd` file. This will limit you to the original kernel version and the original Plymouth boot loader, which is a part of the `initrd` file.

 1. Temporarily  move files that cause the `apt` errors.

        mkdir ~/apt.conf.d
        mv /etc/apt/apt.conf.d/* ~/apt.conf.d/

    Moving these files does not seem to have any negative side effects, based on my testing.

 2. Temporarily  move a file that cause the errors, `update-initramfs: failed for /boot/initrd...` and `Sub-process /usr/bin/dpkg returned an error code (1)`, when upgrading the Linux kernel. (If you are not updating your kernel, you can skip this step; however note that `apt upgrade` will probably include an updated kernel).

        mv /etc/kernel/postinst.d/initramfs-tools ~/

    Moving this file has a negative consequence. The `initrd` for the newer kernel was not generated. As a result, you can not select the new kernel as your ISO boot kernel on the [Kernel tab](https://github.com/PJ-Singh-001/Cubic/wiki/Options-Page#kernel-tab) of the [Options page](https://github.com/PJ-Singh-001/Cubic/wiki/Options-Page). Therefore, your customized Live ISO Environment will use the original kernel. Also, your installed OS will also use the original kernel. However, you can use the newer kernel by executing `update-initramfs -uk all` once the OS has been installed.

 3. Update the packages list.

        apt update

    You will note, there are no `apt` errors this time.

 5. Customize the Linux file system, as you normally would. For example...

        apt upgrade

 6. Update the `initramfs` if you installed a new kernel.

        update-initramfs -uk all

    This doesn't have an effect (see the explanation in step 2), but I always do this anyway.

 7. When you are done with your updates, copy the files back to their original locations. The `-n` flag will not overwrite newer versions.

        mv -n ~/apt.conf.d/* /etc/apt/apt.conf.d/
        mv -n  ~/initramfs-tools /etc/kernel/postinst.d/

**Closed as completed by PJ-Singh-001** 2023-03-26 19:12 UTC
Labels: question
