### ISSUE TITLE
Can a custom iso be used as a starting point for another custom iso

### ISSUE THREAD

**Issue by mikejp56** [PJ-Singh-001/Cubic#325] opened 2024-07-04 22:43 UTC
**Describe the question**

A clear and concise description of what the question is.

**What you have tried**

Steps you already took.

**Expected behavior**

**OS Information (please complete the following information):**
 - OS/Distro Name: [e.g. Ubuntu, Mint, Kubuntu]
 - OS Version [e.g. Ubuntu 21.10]

**Cubic Information (please complete the following information):**
 - Cubic Version: [e.g. 2021.12.67 from the About dialog, or 2021.12-67-release from `dpkg -l`]
 - ISO Customizing: [e.g. ubuntu-21.10-desktop-amd64.iso]
 - Download Link:  The download link for the ISO you are customizing

**Screenshots**

**Comment by PJ-Singh-001** [comment] 2024-07-05 19:14
This seems to be a duplicate of Issue #326.

**Closed as completed by PJ-Singh-001** 2024-07-05 19:14 UTC
Labels: question
