### ISSUE TITLE
unable to locate the compressed Linux file system when use ubuntu-22.04-live-server-amd64.iso

### ISSUE THREAD

**Issue by changchichung** [PJ-Singh-001/Cubic#68] opened 2022-06-10 04:28 UTC
**Describe the question**

unable to locate the compressed Linux file system when use ubuntu-22.04-live-server-amd64.iso

**What you have tried**
redownload the ISO , check the md5sum

**Expected behavior**

**OS Information (please complete the following information):**
 - OS/Distro Name: Ubuntu 
 - OS Version : 22.04.0 amd64 

**Cubic Information (please complete the following information):**
 - Cubic Version: 2021.05.51
 - ISO Customizing: ubuntu-22.04-live-server-amd64.iso
 - Download Link:  https://releases.ubuntu.com/22.04/ubuntu-22.04-live-server-amd64.iso

**Screenshots**
![select the image](https://i.imgur.com/qKOoDJV.png)

![extracting failed](https://i.imgur.com/5z65hAD.png)

any suggestions ?

**Comment by PJ-Singh-001** [comment] 2022-06-11 05:52
https://github.com/PJ-Singh-001/Cubic/issues/19

**Comment by PJ-Singh-001** [comment] 2022-06-11 05:56
This is is a duplicate of (Unable to locate the squashfs file during customization of Ubuntu Server)[https://github.com/PJ-Singh-001/Cubic/issues/19].

The fix was released in Cubic version 2022.01.70. Please upgrade to version 2022.01.70.

**Comment by PJ-Singh-001** [comment] 2022-06-11 05:57
This is is a duplicate of [Unable to locate the squashfs file during customization of Ubuntu Server](https://github.com/PJ-Singh-001/Cubic/issues/19).

The fix was released in Cubic version 2022.01.70. Please upgrade to version 2022.01.70.

**Closed as not planned by PJ-Singh-001** 2022-06-11 05:57 UTC
Labels: duplicate
