### ISSUE TITLE
Apt and flatpak don't work

### ISSUE THREAD

**Issue by sounddrill31** [PJ-Singh-001/Cubic#138] opened 2022-12-07 10:36 UTC
**Describe the bug**

Apt doesn't seem to work. Further issues with flatpak and more

**To Reproduce**

running ```apt update``` and then ```apt install neofetch```(popOS 22.04 amd64)

**Expected behavior**
Should install with no issues?

**OS Information (please complete the following information):**
Host system: ubuntu 18.04(in virtualbox)
ISO: popOS 22.04 amd64 intel

**Cubic Information (please complete the following information):**
Downloaded today, how do I check?

**Cubic Log:**

E: Problem executing scripts APT::Install::Pre-Invoke '[ ! -f /usr/lib/ubuntu-advantage/apt-esm-hook ] || /usr/lib/ubuntu-advantage/apt-esm-hook pre-invoke || true'
E: Sub-process returned an error code
root@cubic:~# 

root@cubic:~# flatpak install flathub com.heroicgameslauncher.hgl

(flatpak install:402): GLib-ERROR **: 16:05:42.166: file ../../../glib/gthread-posix.c: line 1339 (g_system_thread_new): error 'Operation not permitted' during 'pthread_create'
Trace/breakpoint trap (core dumped)
root@cubic:~#

**Comment by PJ-Singh-001** [comment] 2022-12-07 15:00
This is a duplicate of issue #67.

As a work-around, if you are using a virtual machine to run Cubic, use a newer OS than 18.04 as your host OS when customizing Ubuntu based distributions >=20.04.

Both `apt` and Flatpak should work once you do this. Let me know if this is not the case.

**Closed as completed by PJ-Singh-001** 2022-12-07 15:00 UTC
Labels: bug, duplicate

**Comment by sounddrill31** [comment] 2022-12-07 15:03
> This is a duplicate of issue #67.
> 
> As a work-around, if you are using a virtual machine to run Cubic, use a newer OS than 18.04 as your host OS when customizing Ubuntu based distributions >=20.04.
> 
> Both `apt` and Flatpak should work once you do this. Let me know if this is not the case.

Thanks a lot for responding so quick, will reinstall!

**Comment by sounddrill31** [comment] 2022-12-08 03:33
> This is a duplicate of issue #67.
> 
> As a work-around, if you are using a virtual machine to run Cubic, use a newer OS than 18.04 as your host OS when customizing Ubuntu based distributions >=20.04.
> 
> Both `apt` and Flatpak should work once you do this. Let me know if this is not the case.

![image](https://user-images.githubusercontent.com/84176052/206350246-1dae8eb8-da4b-43df-bf43-a4e27817cfa8.png)
Fixed it, Thanks a ton!
