### ISSUE TITLE
Generated ISO fails to boot after installing new kernel

### ISSUE THREAD

**Issue by jkonan100** [PJ-Singh-001/Cubic#71] opened 2022-06-24 08:59 UTC
**Describe the bug**
Used Ubuntu live server point release 20.04.3 as my base OS (in fact I also tried with the 20.04.2 point release).
Installed kernel patches at the customization step. Note that I have tested the kernel patches separately and I know they work.
Selected the just installed kernel at the kernel selection page.
Checked that the boot configuration files (grub.cfg etc...) are correct.
Then tested the generated ISO on a Virtual Machine. All I get is a blank screen, i.e. the resulting ISO doesn't boot.

The generated ISO does not boot.

**To Reproduce**
Steps to reproduce the behavior.
+ use Ubuntu live server point release 20.04.3 as my base OS (in fact I also tried with the 20.04.2 point release).
+ install real time kernel patch
+ select the just installed kernel at the kernel selection page.
+ check that the boot configuration files (grub.cfg, loopback.cfg, txt.cfg etc...) are correct.
+ generate ISO

**Expected behavior**

The ISO image should boot.

**OS Information (please complete the following information):**
 - OS/Distro Name: Ubuntu
 - OS Version: Ubuntu 20.04.3

**Cubic Information (please complete the following information):**
 - Cubic Version: 2021.11.62
 - ISO Customizing: ubuntu-20.04.3-live-server-amd64.iso
 - Download Link:  https://old-releases.ubuntu.com/releases/focal/ubuntu-20.04.3-live-server-amd64.iso

**Cubic Log:**
[Project]
cubic_version = 2021.11-62-release~202111170112~ubuntu20.04.1
create_date = 2022-06-24 08:32
modify_date = 2022-06-24 09:42
directory = /home/julio/work/base_inst_3

[Original]
iso_file_name = ubuntu-20.04.2-live-server-amd64.iso
iso_directory = /home/julio/Downloads
iso_volume_id = Ubuntu-Server 20.04.2 LTS amd64
iso_release_name = Focal Fossa
iso_disk_name = 

[Custom]
iso_version_number = 2022.06.24
iso_file_name = ubuntu-20.04.2-2022.06.24-live-server-amd64.iso
iso_directory = /home/julio/work/base_inst_3
iso_volume_id = Ubuntu-Server 20.04.2 2022.06.24
iso_release_name = Custom Focal Fossa
iso_disk_name = Ubuntu-Server 20.04.2 2022.06.24 "Custom Focal Fossa"

[Status]
is_success_copy = True
is_success_extract = True
iso_template = 789C7D51BB6EC3300CDCFD15DABC94B1F3281AF843BA0A924D394465D190E4204E907FAFE43AADA72EC2E148DD1D49F814E5E3CA761A5052F72C0BA0C097597BEA60D05E00908BE8AFCA36965B65A5094D1D60FF1E9A3B7A96A9678C6F0BEC5F408D43533E34739434A81E65471EDBC87E7E56A3F29122B183FD8E863EF9FD32B29DAD54967A27D86D7936266014F596BB74B95D7C1CB764C03615C4F150400E0F867D8B9083286DB180140C741AE30B02DD511CEAD37999374F21B38C8CF388A2BED5C9AB1565956A96DC74ABB2C6AE5531E5D55BFE05769A5CAA39061C26BB5816CB0B9655F763775A197286614D8436AD852283B271FD85493FA3AAF793AED0D0BAA77FB5CF758EFC77BA740BD02A742A6ED93CFFC584D14EA1F806EEC8B251
casper_directory = casper
squashfs_file_name = filesystem
iso_checksum = 3f9078b0d14ef4c96c1638f7f5a604ed
iso_checksum_file_name = ubuntu-20.04.2-2022.06.24-live-server-amd64.md5

[Options]
update_os_release = True
boot_configurations = boot/grub/grub.cfg,boot/grub/loopback.cfg,isolinux/txt.cfg
compression = gzip

 Cut and paste the log after running `cubic` from the command line

**Screenshots**

**Comment by jkonan100** [comment] 2022-06-24 09:57
Upgraded my Cubic version to Cubic Version: **2022.01.70**.
Same outcome unfortunately.

Kindest Regards,
Jules

**Comment by PJ-Singh-001** [comment] 2022-06-25 00:09
How did you "Installed kernel patches at the customization step" ?

**Comment by jkonan100** [comment] 2022-06-27 05:39
> How did you "Installed kernel patches at the customization step" ?

Hello,

I used the following command:

    dpkg -i linux-headers-5.4.5-*.deb linux-image-5.4.5-*.deb linux-libc-dev_5.4.5-*.deb 

Kindest Regards,
Jules

**Comment by PJ-Singh-001** [comment] 2022-06-27 15:30
And where did you get these `*.deb` file from ?

**Comment by jkonan100** [comment] 2022-06-27 16:50
Hello,

I built them first on a machine with ubuntu-20.04.2 installed, then saved the packages. Note that I am able to install the packages fine. That is, I can boot a Ubuntu 20.04.2 machine, run the above command (the dpkg -i command), reboot and verify (with a uname -a for instance) that the real time kernel has been correctly installed. I can share the packages if that's any help?

Kindest Regards,
Jules

**Comment by jkonan100** [comment] 2022-06-27 16:54
I basically followed the procedure described in the following article to build the debian packages.
https://chenna.me/blog/2020/02/23/how-to-setup-preempt-rt-on-ubuntu-18-04/

Difference is I used ubuntu 20.04 to start with.

Kindest Regards,
Jules

**Comment by PJ-Singh-001** [comment] 2022-06-28 02:06
I noticed you are using a very old version of Cubic.
Is there a reason you are using such an outdated version?

Try using the latest Cubic version 2022.01.70, and let me know what happens?

**Comment by jkonan100** [comment] 2022-06-28 05:10
Hello,

I have also tried version **2022.01.70**. Shortly after raising this issue I realised there was a more up to date version of Cubic (**2022.01.70**), so I upgraded to it (see my second comment above after my original post) but I ended up with the same result.

Kindest Regards,
Jules

**Comment by PJ-Singh-001** [comment] 2022-06-28 14:18
Definitely use Cubic version 2022.01.70.

There was a specific fix to support Ubuntu Server ISOs (for Ununtu 18.04 and above). (See [Unable to locate the squashfs file during customization of Ubuntu Server](https://github.com/PJ-Singh-001/Cubic/issues/19#issuecomment-1019685880)).

I'll try the steps in the [link you shared above](https://github.com/PJ-Singh-001/Cubic/issues/71#issuecomment-1167606764), to see if I can determine what the problem is. It may take me some time.

**Comment by jkonan100** [comment] 2022-06-28 14:31
Hello,

Thanks, yes I am def using version 2022.01.70 these days.

The steps in the article are not too involved. Install the build dependencies, extract the kernel, patch it and build the packages, in essence. I have saved the resulting Debian packages to avoid having to repeat the whole process each time (as a convenience) and the packages install fine on a Ubuntu 20.04.3 (as well as 20.04.2 for instance) system. I can make those Debian packages available to you if that's of any help.

There are no obvious errors at the customization step when building. I am just met with a blank screen when booting. It would be ideal if we could get the resulting ISO from Cubic to boot or perhaps some hints on how to debug it. Many thanks.

Kindest Regards,
Jules

**Comment by PJ-Singh-001** [comment] 2022-06-29 02:43
If you can share your built debian packages, that would save me some time.

**Comment by jkonan100** [comment] 2022-06-29 05:16
Sure thing, I shall try and upload into two parts as there's a file size limit, but please unzip all in same directory.

[package-1.zip](https://github.com/PJ-Singh-001/Cubic/files/9007440/package-1.zip)

**Comment by jkonan100** [comment] 2022-06-29 05:29
Due to the 25MB size limit, I am uploading the files onto a temporary file server.
You can use  the "scp" command to download them.

IP address: 5f130f42421c.mylabserver.com
username: ubuntu
password: ubuntu123

I shall place the files in the **ubuntu** user's home directory so under **/home/ubuntu**.

For completeness:
For instance use the following to download the linux-image-xxx.deb file:
scp ubuntu@5f130f42421c.mylabserver.com:/home/ubuntu/linux-image-5.4.5-rt3-pac6320_5.4.5-rt3-pac6320-1_amd64.deb .

Kindest Regards,
Jules

**Comment by jkonan100** [comment] 2022-06-29 05:36
![Capture_ubuntu](https://user-images.githubusercontent.com/58267482/176359591-943595a9-46f0-44aa-a783-b072244e07a6.PNG)

**Comment by jkonan100** [comment] 2022-06-30 05:24
Hello,

Did you manage to download the packages? The IP address is ephemeral so I have to keep updating my post with the latest one. Do let me know once you have them so I can stop doing that. Many thanks.

Kindest Regards,
Jules

**Comment by PJ-Singh-001** [comment] 2022-06-30 22:30
I just saw your messages now.
I'm not able to get to the files.
I'll try to follow the instructions you linked and build the packages locally.

**Comment by jkonan100** [comment] 2022-07-01 05:30
Hello,

I have updated the IP address section. I have put the **hostname** instead, which in contrast to the IP address is permanent.

Kindest Regards,
Jules

**Comment by PJ-Singh-001** [comment] 2022-07-04 21:53
My DNS server is unable to resolve your hostname.

I tried following the instructions at https://chenna.me/blog/2020/02/23/how-to-setup-preempt-rt-on-ubuntu-18-04/, but I am not able to build the kernel. I keep getting the following error:

    make[2]: *** [debian/rules:7: build-arch] Error 2
    dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
    make[1]: *** [scripts/Makefile.package:77: deb-pkg] Error 2
    make: *** [Makefile:1539: deb-pkg] Error 2

I've tried setting `CONFIG_SYSTEM_TRUSTED_KEYS=""`, `CONFIG_SYSTEM_REVOCATION_KEYS=""`, `CONFIG_DEBUG_INFO_BTF=N`. and `CONFIG_DEBUG_INFO_BTF_MODULES=N`, but this did not help.

**Comment by jkonan100** [comment] 2022-07-05 05:21
Hello,

Yes please give me a shout when you need to access the files so I can ensure the machine is online. The machine does not stay online permanently (that's one of the reasons why the IP address keeps changing). If I put it online now (it is 06:25am now), it will remain online until 10:25am, at which point I would have to switch it back online again for another 4 hours and so on. It is online now, in the meantime I shall try to find a more permanent location. 

Regarding the build error, the error message above does not tell me much I am afraid... I can try and repeat the process on a new machine around lunchtime and see what I get. But it should be possible to build a real-time preemptive kernel.

Kindest Regards,
Jules

**Comment by PJ-Singh-001** [comment] 2022-07-07 02:50
This is what I executed inside Cubic to build the kernel.

The ISO I tried to customize was Ubuntu 20.04.4, and the currently running kernel was 5.15.0-40-generic (same kernel as my host machine running Ubuntu 22.04).

    apt update

    ls -l /boot
    apt install --yes linux-headers-5.15.0-33-generic linux-image-5.15.0-33-generic
    ls -l /boot

    apt install --yes build-essential git libssl-dev libelf-dev
    apt install --yes flex bison

    # https://mirrors.edge.kernel.org/pub/linux/kernel/v5.x/
    wget https://mirrors.edge.kernel.org/pub/linux/kernel/v5.x/linux-5.17.1.tar.xz

    # https://mirrors.edge.kernel.org/pub/linux/kernel/projects/rt/5.17/
    wget https://mirrors.edge.kernel.org/pub/linux/kernel/projects/rt/5.17/patch-5.17.1-rt17.patch.xz

    xz -cd linux-5.17.1.tar.xz | tar xvf -
    cd linux-5.17.1
    xzcat ../patch-5.17.1-rt17.patch.xz | patch -p1

    file /boot/config-5.15.0-33-generic
    cp /boot/config-5.15.0-33-generic .config

    grep -r "CONFIG_SYSTEM_TRUSTED_KEYS" .config
    sed -i 's|CONFIG_SYSTEM_TRUSTED_KEYS="debian/canonical-certs.pem"|CONFIG_SYSTEM_TRUSTED_KEYS=""|g' .config
    grep -r "CONFIG_SYSTEM_TRUSTED_KEYS" .config

    grep -r "CONFIG_SYSTEM_REVOCATION_KEYS" .config
    sed -i 's|CONFIG_SYSTEM_REVOCATION_KEYS="debian/canonical-revoked-certs.pem"|CONFIG_SYSTEM_REVOCATION_KEYS=""|g' .config
    grep -r "CONFIG_SYSTEM_REVOCATION_KEYS" .config

    grep -r "CONFIG_DEBUG_INFO_BTF" .config
    sed -i 's|CONFIG_DEBUG_INFO_BTF=y|CONFIG_DEBUG_INFO_BTF=N|g' .config
    grep -r "CONFIG_DEBUG_INFO_BTF" .config

    grep -r "CONFIG_DEBUG_INFO_BTF_MODULES" .config
    sed -i 's|CONFIG_DEBUG_INFO_BTF_MODULES=y|CONFIG_DEBUG_INFO_BTF_MODULES=N|g' .config
    grep -r "CONFIG_DEBUG_INFO_BTF_MODULES" .config

    make oldconfig

    # Accept defaults for everything, except...
    #     Preemption Model
    #       1. No Forced Preemption (Server) (PREEMPT_NONE)
    #     > 2. Voluntary Kernel Preemption (Desktop) (PREEMPT_VOLUNTARY)
    #       3. Preemptible Kernel (Low-Latency Desktop) (PREEMPT)
    #       4. Fully Preemptible Kernel (Real-Time) (PREEMPT_RT) (NEW)
    #     choice[1-4?]: 4

    make -j8 deb-pkg

**Comment by jkonan100** [comment] 2022-07-07 12:48
Hello,

Apologies for the delay. I have uploaded the files to an always-online server.
**The IP address**: 143.198.248.123
**username**: ubuntu
**password**: ubuntu123

So you should have all the files in there. I shall have a go at rebuilding before I leave my desk. Thanks.
![ls_illustration](https://user-images.githubusercontent.com/58267482/177777035-06e07873-da15-4520-896e-6bca8ac10964.PNG)

Kindest Regards,
Jules

**Comment by PJ-Singh-001** [comment] 2022-07-08 01:22
I was able to download the files.
It may take me a bit of time to try these, so please be patient.

**Comment by jkonan100** [comment] 2022-07-08 05:15
Excellent. Thank you.

Kindest Regards,
Jules

**Comment by PJ-Singh-001** [comment] 2022-07-10 01:58
What happens if you click the [<kbd>Test</kbd> button](https://github.com/PJ-Singh-001/Cubic/wiki/Finish-Test-Page) on the [Finish page](https://github.com/PJ-Singh-001/Cubic/wiki/Finish-Page), after generating a new ISO with the new kernel?

**Comment by PJ-Singh-001** [comment] 2022-07-10 03:50
**Background**

The newer Ubuntu ISOs no longer come with a kernel installed in the Linux filesystem.

Here is the contents of `/boot` from the filesystem of an Ubuntu 20.04.3 ISO (ubuntu-20.04.3-desktop-amd64.iso). As you can see `initrd.img` is a _broken_ symlink to `initrd.img-5.11.0-27-generic`. Also, `vmlinuz` is a _broken_ symlink to `vmlinuz-5.11.0-27-generic`. Both `initrd.img-5.11.0-27-generic` and `vmlinuz-5.11.0-27-generic` do _not_ exist on the filesystem.

    cd /boot
    ls -l | awk '{print $1, $2, $3, $4, $5, "\t", $9, $10, $11}'

    total 6496
    -rw------- 1 root root 5833109 	 System.map-5.11.0-27-generic  
    -rw-r--r-- 1 root root 253599 	 config-5.11.0-27-generic  
    drwxr-xr-x 2 root root 80 	 grub  
    lrwxrwxrwx 1 root root 28 	 initrd.img -> initrd.img-5.11.0-27-generic
    lrwxrwxrwx 1 root root 28 	 initrd.img.old -> initrd.img-5.11.0-27-generic
    -rw-r--r-- 1 root root 182704 	 memtest86+.bin  
    -rw-r--r-- 1 root root 184380 	 memtest86+.elf  
    -rw-r--r-- 1 root root 184884 	 memtest86+_multiboot.bin  
    lrwxrwxrwx 1 root root 25 	 vmlinuz -> vmlinuz-5.11.0-27-generic
    lrwxrwxrwx 1 root root 25 	 vmlinuz.old -> vmlinuz-5.11.0-27-generic

However, the missing kernel files in the `/boot` directory of the Linux filesystem are _not_ needed, because the ISO's file structure does have version 5.11.0-27 of `initrd` and `vmlinuz`, located on the ISO alongside the compressed OS (i.e. the compressed Linux filesystem). These are the kernel files that are used to _bootstrap_ the ISO and start the OS. This is why, when you boot into an unmodified Live ISO, you will see that version 5.11.0-27 of the kernel is running, even though there are no kernel files inside `/boot`.

---

**Option 1**

If you select the default kernel files on the [Kernel tab](https://github.com/PJ-Singh-001/Cubic/wiki/Options-Page#kernel-tab) of Cubic's [Options page](https://github.com/PJ-Singh-001/Cubic/wiki/Options-Page), the ISO's original kernel (version 5.11.0-27) will be used to bootstrap the ISO, and you will be able to log into the Live Environment, _exactly_ as you would with an unmodified ISO.

Because 5.11.0-27 is a newer kernel than your compiled kernel (version 5.4.5), it will be automatically selected by Cubic to be your _bootstrap_ kernel.

<img src="https://user-images.githubusercontent.com/19394936/178130309-98ab681d-f621-4e77-be62-28869f9593d9.png" width="400"/>

Therefore, one option for you is to simply accept the default _bootstrap_ kernel, and your ISO will boot into the Live Environment using this kernel. The drawback is that your compiled kernel will not be running in the Live Environment. Despite this, your custom kernel will still be installed onto you computer when you choose to install Ubuntu, and you can select to boot into your custom kernel when you boot into your installed OS.

<img src="https://user-images.githubusercontent.com/19394936/178130381-a90ddc88-873f-4c40-a909-5bcb66d6b447.png" width="400"/>

---

**Option 2**

I installed your customized kernel using the following commands.

    dpkg -i linux-libc-dev_5.4.5-rt3-pac6320-1_amd64.deb
    dpkg -i linux-headers-5.4.5-rt3-pac6320_5.4.5-rt3-pac6320-1_amd64.deb
    dpkg -i linux-image-5.4.5-rt3-pac6320_5.4.5-rt3-pac6320-1_amd64.deb

Here is the contents of `/boot` after installing the above kernel.

    cd /boot
    ls -l | awk '{print $1, $2, $3, $4, $5, "\t", $9, $10, $11}'

    total 109208
    -rw------- 1 root root 5833109 	 System.map-5.11.0-27-generic  
    -rw-r--r-- 1 root root 4581723 	 System.map-5.4.5-rt3-pac6320  
    -rw-r--r-- 1 root root 253599 	 config-5.11.0-27-generic  
    -rw-r--r-- 1 root root 235775 	 config-5.4.5-rt3-pac6320  
    drwxr-xr-x 2 root root 80 	 grub  
    lrwxrwxrwx 1 root root 28 	 initrd.img -> initrd.img-5.11.0-27-generic
    -rw-r--r-- 1 root root 88915708  initrd.img-5.4.5-rt3-pac6320  
    lrwxrwxrwx 1 root root 28 	 initrd.img.old -> initrd.img-5.11.0-27-generic
    -rw-r--r-- 1 root root 182704 	 memtest86+.bin  
    -rw-r--r-- 1 root root 184380 	 memtest86+.elf  
    -rw-r--r-- 1 root root 184884 	 memtest86+_multiboot.bin  
    lrwxrwxrwx 1 root root 25 	 vmlinuz -> vmlinuz-5.11.0-27-generic
    -rw-r--r-- 1 root root 11438976  vmlinuz-5.4.5-rt3-pac6320  
    lrwxrwxrwx 1 root root 25 	 vmlinuz.old -> vmlinuz-5.11.0-27-generic

As you can see, the new kernel files `vmlinuz-5.4.5-rt3-pac6320` and `vmlinuz-5.4.5-rt3-pac6320` are now present.

In this case, you can select your customized kernel (version 5.4.5) to be the _bootstrap_ kernel on the [Kernel tab](https://github.com/PJ-Singh-001/Cubic/wiki/Options-Page#kernel-tab) of Cubic's [Options page](https://github.com/PJ-Singh-001/Cubic/wiki/Options-Page).

<img src="https://user-images.githubusercontent.com/19394936/178130219-a822cd51-2545-4103-b312-81ef634f0a47.png" width="400"/>

Thus, another option for you is to manually select kernel 5.4.5 as your ISO _bootstrap_ kernel, and your ISO will boot into the Live Environment using this kernel. The benefit is that your compiled kernel will be running in the Live Environment. Your custom kernel will also be installed onto you computer when you choose to install Ubuntu, and you can select to boot into your custom kernel when you boot into your installed OS.

<img src="https://user-images.githubusercontent.com/19394936/178130414-464ba09a-0425-414b-9de0-2912285d672a.png" width="400"/>

**Comment by PJ-Singh-001** [comment] 2022-07-10 04:03
As you can see, I did not have an issue booting into the Live Environment of a customized ISO...
1. with the original kernel, version 5.11.0-27
2. with your customized kernel, version 5.4.5

Please answer these questions...

1. On Cubic's [Kernel tab](https://github.com/PJ-Singh-001/Cubic/wiki/Options-Page#kernel-tab), which kernel did you select as your _bootstrap_ kernel?
2. What happens if you click the [<kbd>Test</kbd> button](https://github.com/PJ-Singh-001/Cubic/wiki/Finish-Test-Page) on the [Finish page](https://github.com/PJ-Singh-001/Cubic/wiki/Finish-Page), after generating a new ISO with the new kernel?
3. Are you making any other changes to the Linux filesystem, other than installing the custom kernel?
4. Are you able to install the customized OS into the Virtual Machine (I presume "No", since you are not able to boot into the Live ISO)?
5. What Virtual Machine are you using to test your ISO?
6. Are you using Legacy Boot, or UEFI?

**Comment by PJ-Singh-001** [comment] 2022-07-10 04:59
I just re-read your initial report, and I see you are using the server version...

So I went back and tested with ubuntu-20.04.3-live-server-arm64.iso.
I couldn't enter the Virtual Environment in Cubic with this ISO. (Perhaps my ISO is corrupt?).

However, with ubuntu-20.04.4-live-server-amd64.iso, I was able to enter the Virtual Environment in Cubic, and I was able to install the custom kernel.

I attempted to boot into the customized ISO, and I disabled the `quiet` boot option, so I could see the verbose output during boot-up.

I see that it is hanging after...

    Begin: Running /scripts/init-premount ... done.

---
If I select kernel 5.4.0-100 (the default bootstrap kernel, I am able to boot into the customized Live ISO.

<img src="https://user-images.githubusercontent.com/19394936/178132040-9e69f9c2-fe7e-4ef3-8ecb-48f63444dc25.png" width="400"/>

As I [explained above](https://github.com/PJ-Singh-001/Cubic/issues/71#issuecomment-1179650092), this kernel is just used to bootstrap your Live ISO. In your case, the custom kernel 5.4.5 is newer, and when you install your OS, the custom kernel is the one that should be installed to the computer.

Have you tried creating an ISO using the default bootstrap kernel, and then installing the customized OS? If so, does it boot into the new kernel?

**Comment by jkonan100** [comment] 2022-07-10 08:18
Hello,

Thanks for giving it a try. Let me try to answer each of your questions. I'll use "Quote Reply" so that the answer goes with the question.

Kindest Regards,
Jules

**Comment by jkonan100** [comment] 2022-07-10 08:25
> I just re-read your initial report, and I see you are using the server version...
> 
> So I went back and tested with ubuntu-20.04.3-live-server-arm64.iso. I couldn't enter the Virtual Environment in Cubic with this ISO. (Perhaps my ISO is corrupt?).
> 
> However, with ubuntu-20.04.4-live-server-amd64.iso, I was able to enter the Virtual Environment in Cubic, and I was able to install the custom kernel.
> 
> I attempted to boot into the customized ISO, and I disabled the `quiet` boot option, so I could see the verbose output during boot-up.
> 
> I see that it is hanging after...
> 
> ```
> Begin: Running /scripts/init-premount ... done.
> ```
> 
> If I select kernel 5.4.0-100 (the default bootstrap kernel, I am able to boot into the customized Live ISO.
> 
> <img src="https://user-images.githubusercontent.com/19394936/178132040-9e69f9c2-fe7e-4ef3-8ecb-48f63444dc25.png" width="400"/>
> 
> As I [explained above](https://github.com/PJ-Singh-001/Cubic/issues/71#issuecomment-1179650092), this kernel is just used to bootstrap your Live ISO. In your case, the custom kernel 5.4.5 is newer, and when you install your OS, the custom kernel is the one that should be installed to the computer.
> 
> Have you tried creating an ISO using the default bootstrap kernel, and then installing the customized OS? If so, does it boot into the new kernel?

I used the Ubuntu live server as my original ISO, but note that I used the "**amd64**" version and not the "**arm64**" as per your post. I think I accidentally used the arm64 at some point but didn't get very far with that and that was an accident as I don't need that architecture.

To your question:
**Have you tried creating an ISO using the default bootstrap kernel, and then installing the customized OS? If so, does it boot into the new kernel?**

I have not tried creating an ISO with Cubic and selecting the bootstrap kernel on the "Kernel" page. So far, I have always picked my custom kernel on the "Kernel" page.

What I have done is to install my custom kernel using the **original Ubuntu live server ISO**, just to test that I could install my custom kernel, i.e. without using Cubic.


Kindest Regards,
Jules

**Comment by jkonan100** [comment] 2022-07-10 08:28
Please find my answers below:

> As you can see, I did not have an issue booting into the Live Environment of a customized ISO...
> 
> 1. with the original kernel, version 5.11.0-27
> 2. with your customized kernel, version 5.4.5
> 
> Please answer these questions...
> 
> 1. On Cubic's [Kernel tab](https://github.com/PJ-Singh-001/Cubic/wiki/Options-Page#kernel-tab), which kernel did you select as your _bootstrap_ kernel?
_I have always picked my custom kernel at this step so far._

> 2. What happens if you click the [Test button](https://github.com/PJ-Singh-001/Cubic/wiki/Finish-Test-Page) on the [Finish page](https://github.com/PJ-Singh-001/Cubic/wiki/Finish-Page), after generating a new ISO with the new kernel?
_I have tried the "Test button" without success, i.e. blank screen._

> 3. Are you making any other changes to the Linux filesystem, other than installing the custom kernel?
_No. Just the custom kernel installation._

> 4. Are you able to install the customized OS into the Virtual Machine (I presume "No", since you are not able to boot into the Live ISO)?
_I am if I use the original Ubuntu live server ISO. I can install that, then install my custom kernel and check that it's working._

> 5. What Virtual Machine are you using to test your ISO?
_Oracle VirtualBox._

> 6. Are you using Legacy Boot, or UEFI?
_UEFI. Legacy Boot is un-ticked by default I believe._


Kindest Regards,
Jules

**Comment by jkonan100** [comment] 2022-07-10 08:49
> `initrd` and `vmlinuz`

Could you please clarify the exact steps for "**Option 2**" again? Specifically, how is "Option 2" different from what I did originally? For instance when you said:

"I installed your customized kernel using the following commands."
_Was that in Cubic at the customization step?_

Many thanks.

Kindest Regards,
Jules

**Comment by PJ-Singh-001** [comment] 2022-07-10 18:46
Option 2 is not different from what you have already done; it's just that what you have done works with the Desktop ISO for 20.04, but not for the Server ISO.

Please understand that selecting a kernel to boot your ISO, and selecting a kernel for your installed OS, are two different things:

 1. Kernel for the Installed OS
    On Cubic's [Terminal page](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page), you can install a kernel. The last kernel you install is the kernel that will be used when you install your OS. In your case, this will be kernel 5.4.5 (from [kernel.org](https://kernel.org/)).

 2. Kernel for the Live Environment
    On Cubic's [Kernel tab](https://github.com/PJ-Singh-001/Cubic/wiki/Options-Page#kernel-tab), you can chose a kernel to boot your ISO. This kernel is used in the Live Environment, but is **not** the kernel that your installed OS uses.

Therefore, you will be fine if you chose Option 1, and simply select the default 5.4.0-100 kernel. Your installed OS will still use kernel 5.4.5 (from [kernel.org](https://kernel.org/)).

**Comment by PJ-Singh-001** [comment] 2022-07-10 19:17
The reason Option 2 is not working is that your _initramfs_ is missing important scripts needed to boot into the Live Environment. However, these scripts are present in the default `initrd` file that comes with the original Ubuntu Server ISO.

<img src="https://user-images.githubusercontent.com/19394936/178158863-67fba65b-3939-47c4-8cbd-8374b11d88e5.png" width="400"/>

**Comment by PJ-Singh-001** [comment] 2022-07-10 19:33
For Option 2 to work, you will need to install the missing files and regenerate your _initramfs_ (i.e. the `/boot/initrd.img` file).

**Instructions**

 1. Download and customize the `ubuntu-20.04.4-live-server-amd64.iso` ISO (_not_ the 20.04.3 ISO, because that version had issues when I tested).

 2. Install the missing scripts (included with the `casper` package).

        apt update
        apt install casper
        dpkg -l casper

        Desired=Unknown/Install/Remove/Purge/Hold
        | Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
        |/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
        ||/ Name           Version      Architecture Description
        +++-==============-============-============-=====================================================
        ii  casper         1.445.1      amd64        Run a "live" preinstalled system from read-only media

 3. Install your customized kernel.
    Note that this will automatically update _initramfs_, so you do not have to do it manually.
    (If you need to manually update _initramfs_, use `update-initramfs -u`).

        dpkg -i linux-libc-dev_5.4.5-*.deb
        dpkg -i linux-headers-5.4.5-rt3-pac6320_5.4.5-*.deb
        dpkg -i linux-image-5.4.5-rt3-pac6320_5.4.5-*.deb

 4. Create missing symlinks in the `/boot` directory for your new kernel files.

        cd /boot
        ln -s vmlinuz-5.4.5-rt3-pac6320 vmlinuz                   
        ln -s initrd.img-5.4.5-rt3-pac6320 initrd.img

        ls -l

        total 62624
        -rw-r--r-- 1 root root  4581723 Jun  9  2021 System.map-5.4.5-rt3-pac6320
        -rw-r--r-- 1 root root   235775 Jun  9  2021 config-5.4.5-rt3-pac6320
        lrwxrwxrwx 1 root root       28 Jul 10 14:18 initrd.img -> initrd.img-5.4.5-rt3-pac6320
        -rw-r--r-- 1 root root 47863754 Jul 10 14:18 initrd.img-5.4.5-rt3-pac6320
        lrwxrwxrwx 1 root root       25 Jul 10 14:18 vmlinuz -> vmlinuz-5.4.5-rt3-pac6320
        -rw-r--r-- 1 root root 11438976 Jun  9  2021 vmlinuz-5.4.5-rt3-pac6320

 5. Finish customizing your OS, as desired.

 6. Optionally remove the `casper` package, since the files were already added to the new `initrd` file, generated in step 3.
    (I would skip this step. This way the `casper` files will always be there, especially if you ever regenerate your _initramfs_).

        # apt autoremove --purge casper

 5. On the [Kernel tab](https://github.com/PJ-Singh-001/Cubic/wiki/Options-Page#kernel-tab), select your new kernel, version 5.4.5.

    <img src="https://user-images.githubusercontent.com/19394936/178158787-03c8523f-5596-4c6b-936b-c270f6439917.png" width="400"/>

 8. Generate your ISO and test.

    <img src="https://user-images.githubusercontent.com/19394936/178158811-d8bc35ab-a5c0-4f27-869c-c64175b2fc34.png" width="400"/>

**Ancillary Note**

When [testing with Cubic](https://github.com/PJ-Singh-001/Cubic/wiki/Finish-Test-Page), the emulator boots into your customized ISO using Legacy BIOS. Therefore, the ISO's grub menu may be modified by editing the `isolinux/txt.cfg` file on [Cubic's Boot tab](https://github.com/PJ-Singh-001/Cubic/wiki/Options-Page#boot-tab).

<img src="https://user-images.githubusercontent.com/19394936/178159193-b984e1a9-8e19-4eb7-a61c-6aae615e4f4d.png" width="400"/>

**Comment by Augusto7743** [comment] 2022-07-10 20:41
I has copied kernel generic to Cubic environment task
sudo dpkg -i *.deb
Works correctly.

You have created the disk partitions used the own customized ISO ?
I see some issues when trying install customized ISO in an disk partitioned with BTRFS used disk utility (gparted live ISO).
The partition created using the kernel from gparted live ISO not is compatible with customized cubic ISO.

**Comment by PJ-Singh-001** [comment] 2022-07-10 21:09
@Augusto7743,

You don't need `sudo` because you are a root user in [Cubic's Virtual Environment](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page).

**Comment by jkonan100** [comment] 2022-07-11 05:22
@PJ-Singh-001 ,

Thanks for the clarifications. As I posted my replies yesterday, I gave it a try. I selected the **default kernel** (instead of my custom kernel) on the "Kernel" tab and was able to boot the generated ISO just fine.

As far as Cubic is concerned, it wasn't a limitation of the software.
Many thanks for your time, I think I should be able to proceed for now.

Kindest Regards,
Jules

**Comment by PJ-Singh-001** [comment] 2022-07-11 14:53
Jules,
Would you please try the [instructions I posted above](https://github.com/PJ-Singh-001/Cubic/issues/71#issuecomment-1179785376) for Option 2, and let me know if it works for you?

**Comment by jkonan100** [comment] 2022-07-11 15:00
@PJ-Singh-001 ,
Shall do. 
However you clarified earlier that the **bootstrap** kernel is different to the **target** kernel, and Option 2 would update the bootstrap kernel. For our purposes I need the target kernel to be correct one so I need to have another think... Let me try a few things tomorrow and get back to you.

Kindest Regards,
Jules

**Comment by PJ-Singh-001** [comment] 2022-07-11 18:13
It’s physically different kernel files.

Cubic lets you use the same kernel version, if you want to. Cubic does this by making a copy the kernel files from your Linux file system (in your case the kernel 5.4.5) onto the boot portion of the ISO.

You were missing files from the `casper` package, which are needed to boot the Live ISO. The instructions above tell you how to install them, to make your kernel ready to be used for Live ISO boot.

**Comment by jkonan100** [comment] 2022-07-12 04:57
Hello @PJ-Singh-001 

"Cubic lets you use the same kernel version, if you want to".
Yes I understood that. The next question for me to answer is whether I actually want/need to use the same kernel for my purpose. That is, I understand from your post that it's technically feasible, I need to figure out the next step. Shall get back to you. Thanks.

Kindest Regards,
Jules

**Comment by PJ-Singh-001** [comment] 2022-07-19 01:57
Closing issue with [solution provided in comment above](https://github.com/PJ-Singh-001/Cubic/issues/71#issuecomment-1179785376).

**Closed as completed by PJ-Singh-001** 2022-07-19 01:57 UTC
Labels: question
