### ISSUE TITLE
can cubic be scripted?

### ISSUE THREAD

**Issue by Islamalastal** [PJ-Singh-001/Cubic#58] opened 2022-05-09 12:44 UTC
Hi, i'm trying to use this great tool! it seems realy useful... but i have a question, can i script it? i mean, can i start cubic in a terminal?

my use case is to make an ubutnu customizer, that can automatic create an iso image, base of an configuration file.

if not, can you please help me and recomended me another tool?

thank you in advance!

**Comment by jeremehancock** [comment] 2022-05-10 14:48
I  use a script within the Cubic Terminal page. So I fire up Cubic and copy the bash file in and run it. It does all my customization. I know that  is not exactly what you are looking for, but wanted to make sure you knew that could be done.

**Comment by PJ-Singh-001** [comment] 2022-05-11 00:04
Duplicate of [Is there a headless mode?](#14)

Cubic does not have a command-line only interface.

As @jeremehancock suggested, the recommended approach is to [copy a script (and other relevant files)](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Copy-Page) into Cubic's [terminal environment](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page), and execute the script from there.

As of version 2022.01.69, Cubic now accepts the following [command-line arguments](https://github.com/PJ-Singh-001/Cubic/wiki/Run-Cubic) which may make it easier to open an existing project (or create a new project) from the command line. But you still have to click through the header bar buttons to generate the ISO.

    usage: cubic [-h] [-v] [-V] [directory] [iso]

    positional arguments:
      directory      directory for a new or existing project
      iso            original ISO file for a new project (ignored for existing projects)

    optional arguments:
      -h, --help     show this help message and exit
      -v, --verbose  output formatted log to the console
      -V, --version  print version information and exit

**Closed as completed by PJ-Singh-001** 2022-05-11 00:04 UTC
Labels: duplicate, question
